'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import communityApiV2 from '@/lib/communityApiV2';

const C={card:'#fff',border:'#DDE6EF',navy:'#10213B',text:'#33465F',muted:'#6B7D91',teal:'#0D9488',tealDark:'#0F766E',tealSoft:'#ECFDF9',blue:'#2563EB',amber:'#B45309',red:'#B42318',green:'#15803D',violet:'#6D28D9'};
const extract=(r:any)=>r?.data?.data??r?.data??null;
const initialForm={name:'',slug:'',description:'',emoji:'🏥',category:'General',visibility:'PUBLIC',language:'en',allowAnonymous:true,requireApproval:false,rules:'',isFeatured:false,isActive:true};

function CommunityModal({item,onClose,onSaved}:{item:any;onClose:()=>void;onSaved:()=>void}){
  const [form,setForm]=useState<any>(item?{...initialForm,...item}:initialForm),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const set=(key:string,value:any)=>setForm((p:any)=>({...p,[key]:value}));
  const save=async()=>{if(!form.name.trim()||(!item&&!form.slug.trim())){setError('Name and slug are required.');return;}setSaving(true);setError('');try{const payload={...form,name:form.name.trim(),slug:form.slug.trim(),description:form.description.trim(),rules:form.rules.trim()};if(item)await api.put(`/admin/communities/${item.id}`,payload);else await api.post('/admin/communities',payload);onSaved();}catch(e:any){setError(e?.response?.data?.message||'Unable to save community.');}finally{setSaving(false);}};
  return <div style={overlay} onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div style={{width:'min(720px,96vw)',maxHeight:'88vh',overflowY:'auto',background:'#fff',borderRadius:20,padding:22}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><h2 style={{margin:0,fontSize:19}}>{item?'Edit community':'Create community'}</h2><button onClick={onClose} style={iconBtn}>×</button></div>{error&&<div style={{...errorBox,marginTop:12}}>{error}</div>}<div style={formGrid}><label style={label}>Name<input value={form.name} onChange={e=>set('name',e.target.value)} style={input}/></label><label style={label}>Slug<input disabled={Boolean(item)} value={form.slug} onChange={e=>set('slug',e.target.value)} placeholder="diabetes-warriors" style={{...input,background:item?'#F4F6F8':'#fff'}}/></label><label style={label}>Emoji<input value={form.emoji} onChange={e=>set('emoji',e.target.value)} style={input}/></label><label style={label}>Category<input value={form.category} onChange={e=>set('category',e.target.value)} style={input}/></label><label style={label}>Visibility<select value={form.visibility} onChange={e=>set('visibility',e.target.value)} style={input}><option>PUBLIC</option><option>RESTRICTED</option><option>PRIVATE</option></select></label><label style={label}>Language<input value={form.language} onChange={e=>set('language',e.target.value)} style={input}/></label></div><label style={label}>Description<textarea value={form.description} onChange={e=>set('description',e.target.value)} rows={3} style={textarea}/></label><label style={label}>Community rules<textarea value={form.rules} onChange={e=>set('rules',e.target.value)} rows={4} style={textarea}/></label><div style={{display:'flex',gap:18,flexWrap:'wrap',marginTop:10}}><Check label="Allow anonymous posting" checked={form.allowAnonymous} onChange={v=>set('allowAnonymous',v)}/><Check label="Require join approval" checked={form.requireApproval} onChange={v=>set('requireApproval',v)}/><Check label="Featured" checked={form.isFeatured} onChange={v=>set('isFeatured',v)}/>{item&&<Check label="Active" checked={form.isActive} onChange={v=>set('isActive',v)}/>}</div><div style={{display:'flex',gap:9,justifyContent:'flex-end',marginTop:18}}><button onClick={onClose} style={secondary}>Cancel</button><button disabled={saving} onClick={save} style={{...primary,opacity:saving?0.65:1}}>{saving?'Saving…':'Save community'}</button></div></div></div>;
}

function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label style={{display:'flex',gap:7,alignItems:'center',fontSize:11.5,fontWeight:700,color:C.text}}><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/>{label}</label>}

function QAModal({community,onClose}:{community:any;onClose:()=>void}){
  const [sessions,setSessions]=useState<any[]>([]),[doctor,setDoctor]=useState(''),[topic,setTopic]=useState(''),[when,setWhen]=useState(''),[duration,setDuration]=useState(60),[link,setLink]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
  const load=useCallback(async()=>{try{const r=await api.get(`/admin/communities/${community.id}/qa-sessions`);setSessions(extract(r)||[]);}catch(e:any){setError(e?.response?.data?.message||'Unable to load Q&A sessions.');}},[community.id]);useEffect(()=>{void load()},[load]);
  const create=async()=>{setSaving(true);setError('');try{await api.post(`/admin/communities/${community.id}/qa-sessions`,{doctorName:doctor,topic,scheduledAt:new Date(when).toISOString(),durationMin:duration,meetLink:link||undefined});setDoctor('');setTopic('');setWhen('');setLink('');await load();}catch(e:any){setError(e?.response?.data?.message||'Unable to schedule Q&A.');}finally{setSaving(false);}};
  const cancel=async(id:string)=>{if(!confirm('Cancel this Q&A session?'))return;try{await api.delete(`/admin/communities/qa-sessions/${id}`);await load();}catch(e:any){setError(e?.response?.data?.message||'Unable to cancel Q&A.');}};
  return <div style={overlay}><div style={{width:'min(760px,96vw)',maxHeight:'88vh',overflowY:'auto',background:'#fff',borderRadius:20,padding:22}}><div style={{display:'flex',justifyContent:'space-between'}}><div><h2 style={{margin:0,fontSize:19}}>Doctor Q&A · {community.name}</h2><div style={{fontSize:11,color:C.muted,marginTop:4}}>Sessions use the real Community Events service and notify opted-in members.</div></div><button onClick={onClose} style={iconBtn}>×</button></div>{error&&<div style={{...errorBox,marginTop:12}}>{error}</div>}<div style={{...formGrid,marginTop:14}}><label style={label}>Doctor / host<input value={doctor} onChange={e=>setDoctor(e.target.value)} style={input}/></label><label style={label}>Topic<input value={topic} onChange={e=>setTopic(e.target.value)} style={input}/></label><label style={label}>Scheduled time<input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)} style={input}/></label><label style={label}>Duration (minutes)<input type="number" min={15} max={240} value={duration} onChange={e=>setDuration(Number(e.target.value))} style={input}/></label></div><label style={label}>Meeting link (optional)<input value={link} onChange={e=>setLink(e.target.value)} placeholder="https://…" style={input}/></label><button disabled={saving||!doctor.trim()||!topic.trim()||!when} onClick={create} style={{...primary,opacity:saving||!doctor.trim()||!topic.trim()||!when?0.6:1}}>Schedule Q&A</button><div style={{borderTop:`1px solid ${C.border}`,marginTop:18,paddingTop:14}}><div style={sectionLabel}>Sessions</div>{sessions.length===0?<div style={emptySmall}>No Q&A sessions scheduled.</div>:sessions.map(s=><div key={s.id} style={{border:`1px solid ${C.border}`,borderRadius:11,padding:11,marginBottom:8,opacity:s.isCancelled?.55:1}}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><b style={{fontSize:12.5}}>{s.topic}</b><div style={{fontSize:10.5,color:C.muted,marginTop:3}}>{s.doctorName} · {new Date(s.scheduledAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})} · {s.durationMin} min</div></div>{!s.isCancelled&&<button onClick={()=>cancel(s.id)} style={{...miniBtn,color:C.red}}>Cancel</button>}</div></div>)}</div></div></div>;
}

export default function AdminCommunitiesV2(){
  const [tab,setTab]=useState<'communities'|'requests'|'moderation'|'analytics'>('communities'),[communities,setCommunities]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [search,setSearch]=useState(''),[edit,setEdit]=useState<any>(null),[creating,setCreating]=useState(false),[qa,setQa]=useState<any>(null),[reqStatus,setReqStatus]=useState<'PENDING'|'APPROVED'|'REJECTED'>('PENDING');
  const [modCommunity,setModCommunity]=useState<any>(null),[reports,setReports]=useState<any[]>([]),[reportsLoading,setReportsLoading]=useState(false);

  const loadCommunities=useCallback(async()=>{setLoading(true);setError('');try{const r=await api.get('/admin/communities');setCommunities(extract(r)||[]);}catch(e:any){setCommunities([]);setError(e?.response?.data?.message||'Unable to load communities.');}finally{setLoading(false);}},[]);
  const loadRequests=useCallback(async(status=reqStatus)=>{try{const r=await api.get('/admin/communities/requests',{params:{status,limit:100}});const data=extract(r);setRequests(data?.requests||[]);}catch(e:any){setRequests([]);setError(e?.response?.data?.message||'Unable to load community requests.');}},[reqStatus]);
  useEffect(()=>{void loadCommunities();},[loadCommunities]);useEffect(()=>{if(tab==='requests')void loadRequests(reqStatus);},[tab,reqStatus,loadRequests]);
  const filtered=useMemo(()=>communities.filter(c=>!search.trim()||`${c.name} ${c.category} ${c.slug}`.toLowerCase().includes(search.toLowerCase())),[communities,search]);
  const pendingRequests=useMemo(()=>requests.filter(r=>r.status==='PENDING').length,[requests]);

  const toggle=async(c:any,key:'toggle'|'feature')=>{setError('');try{await api.patch(`/admin/communities/${c.id}/${key}`);await loadCommunities();}catch(e:any){setError(e?.response?.data?.message||'Unable to update community.');}};
  const archive=async(c:any)=>{if(!confirm(`Archive ${c.name}?`))return;try{await api.delete(`/admin/communities/${c.id}`,{data:{hard:false}});await loadCommunities();setNotice(`${c.name} archived.`);}catch(e:any){setError(e?.response?.data?.message||'Unable to archive community.');}};
  const approve=async(r:any)=>{const note=prompt('Admin note (optional):')??'';try{await api.post(`/admin/communities/requests/${r.id}/approve`,{adminNote:note});setNotice(`${r.communityName||r.name} approved and created.`);await Promise.all([loadRequests(reqStatus),loadCommunities()]);}catch(e:any){setError(e?.response?.data?.message||'Unable to approve request.');}};
  const reject=async(r:any)=>{const reason=prompt('Reason for rejection:');if(!reason?.trim())return;try{await api.post(`/admin/communities/requests/${r.id}/reject`,{reason:reason.trim()});setNotice('Request rejected and requester notified.');await loadRequests(reqStatus);}catch(e:any){setError(e?.response?.data?.message||'Unable to reject request.');}};
  const loadReports=async(c:any)=>{setModCommunity(c);setReportsLoading(true);setError('');try{const r:any=await communityApiV2.reports(c.id,'PENDING');setReports(Array.isArray(r)?r:[]);}catch(e:any){setReports([]);setError(e?.response?.data?.message||'Unable to load reports.');}finally{setReportsLoading(false);}};
  const resolve=async(r:any,action:'DISMISS'|'DELETE_CONTENT')=>{const reason=prompt(action==='DISMISS'?'Why is this report being dismissed?':'Reason for removing the reported content:');if(!reason?.trim()||!modCommunity)return;try{await communityApiV2.resolveReport(modCommunity.id,r.id,{action,resolution:reason.trim()});setReports(prev=>prev.filter(x=>x.id!==r.id));setNotice(action==='DISMISS'?'Report dismissed.':'Content removed and moderation action logged.');}catch(e:any){setError(e?.response?.data?.message||'Unable to resolve report.');}};

  return <div style={{fontFamily:"'Inter',system-ui,sans-serif",color:C.navy}}><div style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'flex-start',flexWrap:'wrap',marginBottom:18}}><div><h1 style={{fontSize:24,margin:0}}>Community Operations</h1><p style={{fontSize:12,color:C.muted,margin:'5px 0 0'}}>Manage real communities, requests, clinical Q&A and moderation.</p></div><button onClick={()=>setCreating(true)} style={primary}>+ Create Community</button></div>{notice&&<div style={noticeBox}>{notice}<button onClick={()=>setNotice('')} style={plain}>×</button></div>}{error&&<div style={errorBox}>{error}<button onClick={()=>setError('')} style={plain}>×</button></div>}
    <div style={{display:'flex',gap:4,background:'#EDF1F5',borderRadius:11,padding:4,width:'fit-content',marginBottom:17}}>{([['communities','Communities'],['requests','Requests'],['moderation','Moderation'],['analytics','Analytics']] as const).map(([key,label])=><button key={key} onClick={()=>setTab(key)} style={{border:0,borderRadius:8,padding:'8px 14px',background:tab===key?'#fff':'transparent',fontSize:12,fontWeight:tab===key?800:650,color:tab===key?C.navy:C.muted,cursor:'pointer'}}>{label}{key==='requests'&&pendingRequests>0?` (${pendingRequests})`:''}</button>)}</div>

    {tab==='communities'&&<><div style={{display:'flex',gap:9,marginBottom:13}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search communities" style={{...input,flex:1}}/><button onClick={()=>void loadCommunities()} style={secondary}>Refresh</button></div>{loading?<div style={empty}>Loading…</div>:<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(310px,1fr))',gap:11}}>{filtered.map(c=><div key={c.id} style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div style={{display:'flex',gap:9}}><span style={{fontSize:25}}>{c.emoji||'🏥'}</span><div><b style={{fontSize:13.5}}>{c.name}</b><div style={{fontSize:10,color:C.muted}}>{c.slug} · {c.category||'General'}</div></div></div><div style={{display:'flex',gap:4}}><span style={{...pill,background:c.isActive?'#F0FDF4':'#FFF5F5',color:c.isActive?C.green:C.red}}>{c.isActive?'Active':'Inactive'}</span>{c.isFeatured&&<span style={{...pill,background:'#FFF8E8',color:C.amber}}>Featured</span>}</div></div><p style={{fontSize:11.5,color:C.text,lineHeight:1.5,minHeight:48}}>{c.description}</p><div style={{display:'flex',gap:14,fontSize:10.5,color:C.muted,borderTop:`1px solid ${C.border}`,paddingTop:9}}><span>👥 {c._count?.members||0}</span><span>💬 {c._count?.posts||0}</span><span>{c.visibility}</span></div><div style={{display:'flex',gap:6,flexWrap:'wrap',marginTop:11}}><button onClick={()=>setEdit(c)} style={miniBtn}>Edit</button><button onClick={()=>toggle(c,'feature')} style={miniBtn}>{c.isFeatured?'Unfeature':'Feature'}</button><button onClick={()=>setQa(c)} style={miniBtn}>Doctor Q&A</button><button onClick={()=>loadReports(c)} style={miniBtn}>Reports</button><button onClick={()=>toggle(c,'toggle')} style={miniBtn}>{c.isActive?'Deactivate':'Activate'}</button><button onClick={()=>archive(c)} style={{...miniBtn,color:C.red}}>Archive</button></div></div>)}</div>}</>}

    {tab==='requests'&&<><div style={{display:'flex',gap:6,marginBottom:13}}>{(['PENDING','APPROVED','REJECTED'] as const).map(s=><button key={s} onClick={()=>setReqStatus(s)} style={{...secondary,background:reqStatus===s?C.tealSoft:'#fff',color:reqStatus===s?C.tealDark:C.text}}>{s}</button>)}</div>{requests.length===0?<div style={empty}>No {reqStatus.toLowerCase()} requests.</div>:<div style={{display:'grid',gap:9}}>{requests.map(r=><div key={r.id} style={panel}><div style={{display:'flex',justifyContent:'space-between',gap:10}}><div><b style={{fontSize:13.5}}>{r.communityName||r.name}</b><div style={{fontSize:10.5,color:C.muted,marginTop:2}}>{r.category||'General'} · {r.requesterEmail||'Authenticated user'}</div></div><span style={pill}>{r.status}</span></div><p style={{fontSize:11.8,lineHeight:1.5,color:C.text}}>{r.reason}</p>{r.adminNote&&<div style={{fontSize:10.5,color:C.muted,background:'#F7F9FB',padding:8,borderRadius:8}}>Admin note: {r.adminNote}</div>}{r.status==='PENDING'&&<div style={{display:'flex',gap:7,marginTop:10}}><button onClick={()=>reject(r)} style={{...secondary,color:C.red}}>Reject</button><button onClick={()=>approve(r)} style={primary}>Approve & Create</button></div>}</div>)}</div>}</>}

    {tab==='moderation'&&<div className="hc-admin-mod-grid" style={{display:'grid',gridTemplateColumns:'290px minmax(0,1fr)',gap:14,alignItems:'start'}}><div style={panel}><div style={sectionLabel}>Choose community</div><div style={{display:'grid',gap:5}}>{communities.filter(c=>c.isActive).map(c=><button key={c.id} onClick={()=>loadReports(c)} style={{textAlign:'left',border:`1px solid ${modCommunity?.id===c.id?'#A8DDD6':C.border}`,background:modCommunity?.id===c.id?C.tealSoft:'#fff',borderRadius:9,padding:'8px 9px',fontSize:11.5,fontWeight:700,color:C.text,cursor:'pointer'}}>{c.emoji} {c.name}</button>)}</div></div><div>{!modCommunity?<div style={empty}>Select a community to inspect its pending safety reports.</div>:reportsLoading?<div style={empty}>Loading moderation queue…</div>:reports.length===0?<div style={empty}>No pending reports for {modCommunity.name}.</div>:<div style={{display:'grid',gap:9}}>{reports.map(r=><div key={r.id} style={panel}><div style={{display:'flex',justifyContent:'space-between'}}><b style={{fontSize:12.5}}>{r.reason}</b><span style={pill}>{r.targetType}</span></div><div style={{fontSize:11.5,color:C.text,margin:'7px 0'}}>{r.details||'No additional details supplied.'}</div><div style={{fontSize:10,color:C.muted}}>Target: {r.targetId}</div><div style={{display:'flex',gap:7,marginTop:10}}><button onClick={()=>resolve(r,'DISMISS')} style={secondary}>Dismiss</button><button onClick={()=>resolve(r,'DELETE_CONTENT')} style={{...primary,background:C.red}}>Remove content</button></div></div>)}</div>}</div></div>}

    {tab==='analytics'&&<div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10,marginBottom:15}}>{[{label:'Communities',value:communities.length,color:C.teal},{label:'Active',value:communities.filter(c=>c.isActive).length,color:C.green},{label:'Featured',value:communities.filter(c=>c.isFeatured).length,color:C.amber},{label:'Members',value:communities.reduce((n,c)=>n+(c._count?.members||0),0),color:C.blue},{label:'Posts',value:communities.reduce((n,c)=>n+(c._count?.posts||0),0),color:C.violet}].map(s=><div key={s.label} style={{...panel,borderTop:`3px solid ${s.color}`}}><div style={sectionLabel}>{s.label}</div><div style={{fontSize:27,fontWeight:900,color:s.color}}>{Number(s.value).toLocaleString('en-IN')}</div></div>)}</div><div style={panel}><div style={sectionLabel}>Community size</div>{[...communities].sort((a,b)=>(b._count?.members||0)-(a._count?.members||0)).slice(0,12).map(c=><div key={c.id} style={{display:'flex',justifyContent:'space-between',gap:10,borderTop:`1px solid ${C.border}`,padding:'8px 0',fontSize:11.5}}><span>{c.emoji} {c.name}</span><b>{c._count?.members||0} members</b></div>)}</div></div>}
    {(creating||edit)&&<CommunityModal item={edit||null} onClose={()=>{setCreating(false);setEdit(null)}} onSaved={async()=>{setCreating(false);setEdit(null);await loadCommunities();setNotice('Community saved.')}}/>}{qa&&<QAModal community={qa} onClose={()=>setQa(null)}/>}<style>{`@media(max-width:820px){.hc-admin-mod-grid{grid-template-columns:1fr!important}}`}</style>
  </div>;
}

const panel:React.CSSProperties={background:C.card,border:`1px solid ${C.border}`,borderRadius:13,padding:14,boxShadow:'0 1px 6px rgba(15,31,56,.04)'};
const primary:React.CSSProperties={border:0,borderRadius:8,padding:'8px 11px',background:`linear-gradient(135deg,${C.tealDark},${C.teal})`,color:'#fff',fontSize:11.5,fontWeight:800,cursor:'pointer'};
const secondary:React.CSSProperties={border:`1px solid ${C.border}`,borderRadius:8,padding:'7px 10px',background:'#fff',color:C.text,fontSize:11.5,fontWeight:700,cursor:'pointer'};
const miniBtn:React.CSSProperties={border:`1px solid ${C.border}`,borderRadius:7,padding:'5px 8px',background:'#F9FBFD',color:C.text,fontSize:10.5,fontWeight:700,cursor:'pointer'};
const input:React.CSSProperties={width:'100%',boxSizing:'border-box',border:`1px solid ${C.border}`,borderRadius:9,padding:'8px 9px',fontSize:11.5,color:C.navy,background:'#fff',outline:'none',marginTop:5};
const textarea:React.CSSProperties={...input,resize:'vertical'};
const label:React.CSSProperties={fontSize:10.5,fontWeight:800,color:C.text,textTransform:'uppercase',letterSpacing:'.05em'};
const formGrid:React.CSSProperties={display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:10,marginBottom:10};
const sectionLabel:React.CSSProperties={fontSize:10,fontWeight:850,letterSpacing:'.08em',textTransform:'uppercase',color:C.muted,marginBottom:8};
const pill:React.CSSProperties={borderRadius:999,padding:'3px 7px',fontSize:9.5,fontWeight:800,background:C.tealSoft,color:C.tealDark};
const empty:React.CSSProperties={background:'#fff',border:`1px dashed ${C.border}`,borderRadius:13,padding:'32px 16px',textAlign:'center',fontSize:12,color:C.muted};
const emptySmall:React.CSSProperties={border:`1px dashed ${C.border}`,borderRadius:10,padding:18,textAlign:'center',fontSize:11.5,color:C.muted};
const overlay:React.CSSProperties={position:'fixed',inset:0,zIndex:2500,display:'grid',placeItems:'center',background:'rgba(15,31,56,.48)',padding:18};
const iconBtn:React.CSSProperties={width:33,height:33,borderRadius:8,border:`1px solid ${C.border}`,background:'#F8FAFC',fontSize:19,cursor:'pointer'};
const noticeBox:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:10,background:C.tealSoft,border:'1px solid #B8EEE6',color:C.tealDark,borderRadius:10,padding:'9px 12px',fontSize:11.5,marginBottom:12};
const errorBox:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:10,background:'#FFF5F5',border:'1px solid #FECACA',color:C.red,borderRadius:10,padding:'9px 12px',fontSize:11.5,marginBottom:12};
const plain:React.CSSProperties={border:0,background:'none',color:'currentColor',fontWeight:900,cursor:'pointer'};
