'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import PublicNavbar from '@/components/PublicNavbar';
import { useAuthStore } from '@/store/authStore';
import communityApiV2 from '@/lib/communityApiV2';

const C={page:'#F5F7FA',card:'#fff',border:'#DDE6EF',navy:'#10213B',text:'#33465F',muted:'#6B7D91',teal:'#0D9488',tealDark:'#0F766E',tealSoft:'#ECFDF9',blue:'#2563EB',amber:'#B45309',red:'#B42318',green:'#15803D',violet:'#6D28D9'};
const reactions=[['LIKE','👍','Like'],['SUPPORT','💚','Support'],['HELPFUL','💡','Helpful']] as const;

function dateTime(value:string){return new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(value));}
function ago(value:string){const s=Math.max(0,(Date.now()-new Date(value).getTime())/1000);if(s<60)return'Just now';if(s<3600)return`${Math.floor(s/60)}m ago`;if(s<86400)return`${Math.floor(s/3600)}h ago`;return`${Math.floor(s/86400)}d ago`;}
function getStatus(c:any){return c?.membershipStatus||(c?.isJoined||c?.is_joined?'JOINED':'NOT_JOINED');}

function CommentDrawer({post,onClose,canWrite,allowAnonymous,onCountChanged}:{post:any;onClose:()=>void;canWrite:boolean;allowAnonymous:boolean;onCountChanged:(n:number)=>void}){
  const [rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[body,setBody]=useState(''),[anon,setAnon]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const r:any=await communityApiV2.comments(post.id);setRows(Array.isArray(r)?r:[]);}catch(e:any){setError(e?.response?.data?.message||'Unable to load replies.');}finally{setLoading(false);}},[post.id]);
  useEffect(()=>{void load();},[load]);
  const submit=async()=>{if(!body.trim())return;setSaving(true);setError('');try{await communityApiV2.addComment(post.id,{body:body.trim(),isAnonymous:anon});setBody('');setAnon(false);await load();onCountChanged((post.comment_count||0)+1);}catch(e:any){setError(e?.response?.data?.message||'Unable to add your reply.');}finally{setSaving(false);}};
  return <div onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}} style={overlay}><div style={{width:'min(650px,96vw)',maxHeight:'88vh',overflowY:'auto',background:'#fff',borderRadius:20,padding:22,boxShadow:'0 24px 70px rgba(15,31,56,.25)'}}>
    <div style={{display:'flex',justifyContent:'space-between',gap:12,alignItems:'center'}}><div><b style={{fontSize:18,color:C.navy}}>Replies</b><div style={{fontSize:11.5,color:C.muted,marginTop:3}}>Real community discussion</div></div><button onClick={onClose} style={iconButton}>×</button></div>
    {error&&<div style={{...errorBox,marginTop:14}}>{error}</div>}
    {loading?<div style={emptySmall}>Loading replies…</div>:rows.length===0?<div style={emptySmall}>No replies yet. Start the conversation.</div>:<div style={{display:'grid',gap:9,marginTop:16}}>{rows.map((r:any)=><div key={r.id} style={{border:`1px solid ${C.border}`,borderRadius:12,padding:12,background:'#FAFCFE'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><b style={{fontSize:12,color:C.navy}}>{r.author_name||'HealthConnect Member'}</b><span style={{fontSize:10,color:C.muted}}>{ago(r.createdAt)}</span></div><div style={{fontSize:12.5,lineHeight:1.55,color:C.text,marginTop:5}}>{r.body}</div>{r.replies?.length>0&&<div style={{borderLeft:'2px solid #DDE6EF',paddingLeft:10,marginTop:9,display:'grid',gap:7}}>{r.replies.map((reply:any)=><div key={reply.id}><b style={{fontSize:11.5,color:C.navy}}>{reply.author_name}</b><div style={{fontSize:12,color:C.text}}>{reply.body}</div></div>)}</div>}</div>)}</div>}
    {canWrite&&<div style={{borderTop:`1px solid ${C.border}`,marginTop:18,paddingTop:16}}><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={3000} rows={3} placeholder="Add a helpful, respectful reply" style={textarea}/>{allowAnonymous&&<label style={{display:'flex',gap:7,alignItems:'center',fontSize:11.5,color:C.text,marginTop:8}}><input type="checkbox" checked={anon} onChange={e=>setAnon(e.target.checked)}/> Reply anonymously</label>}<button disabled={saving||!body.trim()} onClick={submit} style={{...primary,marginTop:10,opacity:saving||!body.trim()?.6:1}}>{saving?'Posting…':'Post reply'}</button></div>}
  </div></div>;
}

function CreatePost({community,onCreated,onClose}:{community:any;onCreated:()=>void;onClose:()=>void}){
  const [title,setTitle]=useState(''),[body,setBody]=useState(''),[anon,setAnon]=useState(false),[tags,setTags]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const submit=async()=>{if(!body.trim())return;setSaving(true);setError('');try{await communityApiV2.createPost(community.id,{title:title.trim()||undefined,body:body.trim(),tags:tags.split(',').map(x=>x.trim()).filter(Boolean).slice(0,12),isAnonymous:anon});onCreated();}catch(e:any){setError(e?.response?.data?.message||'Unable to publish your post.');}finally{setSaving(false);}};
  return <div style={overlay} onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><div style={{width:'min(620px,96vw)',background:'#fff',borderRadius:20,padding:23,boxShadow:'0 24px 70px rgba(15,31,56,.25)'}}><div style={{display:'flex',justifyContent:'space-between'}}><div><h2 style={{fontSize:19,margin:0,color:C.navy}}>Share with {community.name}</h2><div style={{fontSize:11.5,color:C.muted,marginTop:4}}>Experiences and questions are welcome. Avoid prescribing treatment to others.</div></div><button onClick={onClose} style={iconButton}>×</button></div>{error&&<div style={{...errorBox,marginTop:14}}>{error}</div>}<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={180} placeholder="Title (optional)" style={{...input,marginTop:16}}/><textarea value={body} onChange={e=>setBody(e.target.value)} maxLength={10000} rows={6} placeholder="What would you like to share?" style={{...textarea,marginTop:10}}/><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="Tags, separated by commas" style={{...input,marginTop:10}}/>{community.allowAnonymous&&<label style={{display:'flex',alignItems:'center',gap:7,fontSize:11.5,color:C.text,marginTop:10}}><input type="checkbox" checked={anon} onChange={e=>setAnon(e.target.checked)}/> Post anonymously</label>}<div style={{display:'flex',gap:10,marginTop:17}}><button onClick={onClose} style={{...secondary,flex:1}}>Cancel</button><button onClick={submit} disabled={saving||!body.trim()} style={{...primary,flex:2,opacity:saving||!body.trim()?.6:1}}>{saving?'Publishing…':'Publish post'}</button></div></div></div>;
}

export default function CommunityDetailV2(){
  const params=useParams();const router=useRouter();const ref=String(params?.slug||'');
  const user=useAuthStore(s=>(s as any).user);const authenticated=useAuthStore(s=>(s as any).isAuthenticated);
  const [community,setCommunity]=useState<any>(null),[posts,setPosts]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[health,setHealth]=useState<any>(null);
  const [loading,setLoading]=useState(true),[feedLoading,setFeedLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [sort,setSort]=useState<'newest'|'popular'>('newest'),[joining,setJoining]=useState(false),[createOpen,setCreateOpen]=useState(false),[commentPost,setCommentPost]=useState<any>(null),[busyPost,setBusyPost]=useState<string|null>(null);
  const [reports,setReports]=useState<any[]>([]),[showModeration,setShowModeration]=useState(false);

  const signIn=()=>{sessionStorage.setItem('hc_post_login_redirect',`/communities/${ref}`);window.location.href='/?auth=login';};
  const loadCommunity=useCallback(async()=>{setLoading(true);setError('');try{const c:any=await communityApiV2.get(ref);setCommunity(c);}catch(e:any){setCommunity(null);setError(e?.response?.data?.message||'Community not found or unavailable.');}finally{setLoading(false);}},[ref]);
  const loadFeed=useCallback(async(c:any)=>{setFeedLoading(true);try{const [p,e,h]=await Promise.allSettled([communityApiV2.posts(c.id,{sort,limit:30}),communityApiV2.events(c.id),communityApiV2.healthScore(c.id)]);if(p.status==='fulfilled')setPosts(Array.isArray((p.value as any)?.posts)?(p.value as any).posts:[]);else setPosts([]);if(e.status==='fulfilled')setEvents(Array.isArray(e.value)?e.value:[]);else setEvents([]);if(h.status==='fulfilled')setHealth(h.value);else setHealth(null);}finally{setFeedLoading(false);}},[sort]);
  useEffect(()=>{void loadCommunity();},[loadCommunity]);useEffect(()=>{if(community?.id)void loadFeed(community);},[community?.id,loadFeed]);

  const state=getStatus(community);const joined=state==='JOINED';const pending=state==='PENDING_APPROVAL';const role=String(community?.membershipRole||'').toUpperCase();const canModerate=user?.role==='ADMIN'||['MODERATOR','OWNER','ADMIN'].includes(role);const contentAccessible=community?.visibility==='PUBLIC'||joined||user?.role==='ADMIN';

  const join=async()=>{if(!authenticated){signIn();return;}setJoining(true);setError('');try{const result:any=await communityApiV2.join(community.id);await loadCommunity();setNotice(result?.membershipStatus==='PENDING_APPROVAL'?'Join request submitted for moderator approval.':'You joined this community.');}catch(e:any){setError(e?.response?.data?.message||'Unable to join community.');}finally{setJoining(false);}};
  const leave=async()=>{setJoining(true);setError('');try{await communityApiV2.leave(community.id);setNotice('You left this community.');await loadCommunity();}catch(e:any){setError(e?.response?.data?.message||'Unable to leave community.');}finally{setJoining(false);}};
  const react=async(post:any,type:'LIKE'|'SUPPORT'|'HELPFUL')=>{if(!authenticated){signIn();return;}setBusyPost(post.id);setError('');try{const result:any=await communityApiV2.react(post.id,type);setPosts(prev=>prev.map(p=>p.id===post.id?{...p,reactions:result.reactions,userReactions:result.userReactions,user_reaction:result.userReactions?.[0]||null}:p));}catch(e:any){setError(e?.response?.data?.message||'Unable to update reaction.');}finally{setBusyPost(null);}};
  const report=async(post:any)=>{if(!authenticated){signIn();return;}const details=window.prompt('Briefly describe the problem with this post.');if(details===null)return;try{await communityApiV2.report(community.id,{targetType:'POST',targetId:post.id,reason:'OTHER',details:details.trim()||undefined});setNotice('Report submitted to community moderators.');}catch(e:any){setError(e?.response?.data?.message||'Unable to submit report.');}};
  const removePost=async(post:any)=>{if(!window.confirm('Remove this post from the community?'))return;setBusyPost(post.id);try{await communityApiV2.deletePost(community.id,post.id);setPosts(prev=>prev.filter(p=>p.id!==post.id));setNotice('Post removed.');}catch(e:any){setError(e?.response?.data?.message||'Unable to remove post.');}finally{setBusyPost(null);}};
  const pin=async(post:any)=>{setBusyPost(post.id);try{const r:any=await communityApiV2.pinPost(community.id,post.id);setPosts(prev=>prev.map(p=>p.id===post.id?{...p,isPinned:r.isPinned}:p));}catch(e:any){setError(e?.response?.data?.message||'Unable to update pin.');}finally{setBusyPost(null);}};
  const rsvp=async(event:any,status:'GOING'|'MAYBE')=>{if(!authenticated){signIn();return;}try{await communityApiV2.rsvpEvent(event.id,status);setEvents(prev=>prev.map(e=>e.id===event.id?{...e,myRsvp:status}:e));}catch(e:any){setError(e?.response?.data?.message||'Unable to update RSVP.');}};
  const loadReports=async()=>{try{const r:any=await communityApiV2.reports(community.id);setReports(Array.isArray(r)?r:[]);setShowModeration(true);}catch(e:any){setError(e?.response?.data?.message||'Unable to load moderation queue.');}};
  const resolve=async(reportRow:any,action:'DISMISS'|'DELETE_CONTENT')=>{const note=window.prompt(action==='DISMISS'?'Reason for dismissing report:':'Moderation reason for removing content:');if(!note?.trim())return;try{await communityApiV2.resolveReport(community.id,reportRow.id,{action,resolution:note.trim()});setReports(prev=>prev.filter(r=>r.id!==reportRow.id));if(action==='DELETE_CONTENT'&&reportRow.targetType==='POST')setPosts(prev=>prev.filter(p=>p.id!==reportRow.targetId));}catch(e:any){setError(e?.response?.data?.message||'Unable to resolve report.');}};

  if(loading)return <div style={centerPage}>Loading community…</div>;
  if(!community)return <div style={centerPage}><div style={{textAlign:'center'}}><div style={{fontSize:42}}>🔍</div><h2>{error||'Community not found'}</h2><button onClick={()=>router.push('/communities')} style={primary}>Back to Communities</button></div></div>;

  return <div style={{minHeight:'100vh',background:C.page,fontFamily:"'Inter','Poppins',system-ui,sans-serif",color:C.navy}}><PublicNavbar/><main style={{paddingTop:64}}>
    <section style={{background:'linear-gradient(135deg,#EAF9F6,#FFFFFF)',borderBottom:`1px solid ${C.border}`}}><div style={{maxWidth:1180,margin:'0 auto',padding:'28px 5%'}}><button onClick={()=>router.push('/communities')} style={secondary}>← All communities</button><div style={{display:'flex',gap:18,alignItems:'flex-start',marginTop:18,flexWrap:'wrap'}}><div style={{width:68,height:68,borderRadius:18,background:C.tealSoft,display:'grid',placeItems:'center',fontSize:34,border:'1px solid #B8EEE6'}}>{community.emoji||'🏥'}</div><div style={{flex:1,minWidth:250}}><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><h1 style={{fontSize:'clamp(25px,4vw,36px)',margin:0,color:C.navy}}>{community.name}</h1>{community.isFeatured&&<span style={pill}>Featured</span>}{joined&&<span style={{...pill,background:'#F0FDF4',color:C.green}}>✓ Joined</span>}{pending&&<span style={{...pill,background:'#FFF8E8',color:C.amber}}>Approval pending</span>}</div><p style={{maxWidth:760,fontSize:13.5,lineHeight:1.65,color:C.text,margin:'8px 0 12px'}}>{community.description}</p><div style={{display:'flex',gap:14,flexWrap:'wrap',fontSize:11.5,color:C.muted}}><span>👥 {(community.member_count||0).toLocaleString('en-IN')} members</span><span>💬 {(community.post_count||0).toLocaleString('en-IN')} posts</span><span>{community.visibility==='PUBLIC'?'🌐 Public':community.visibility==='RESTRICTED'?'🛡️ Approval required':'🔒 Private'}</span>{community.allowAnonymous&&<span>🎭 Anonymous posting available</span>}</div></div><div style={{display:'flex',gap:8}}>{joined?<button disabled={joining} onClick={leave} style={secondary}>{joining?'Working…':'Leave'}</button>:community.visibility!=='PRIVATE'&&<button disabled={joining||pending} onClick={join} style={{...primary,opacity:pending?.65:1}}>{joining?'Working…':pending?'Request pending':'Join community'}</button>}{joined&&<button onClick={()=>setCreateOpen(true)} style={primary}>+ New post</button>}</div></div></div></section>

    <div style={{maxWidth:1180,margin:'0 auto',padding:'22px 5% 70px'}}>{notice&&<div style={noticeBox}>{notice}<button onClick={()=>setNotice('')} style={plainX}>×</button></div>}{error&&<div style={errorBox}>{error}<button onClick={()=>setError('')} style={plainX}>×</button></div>}
      {!contentAccessible?<div style={{...panel,padding:34,textAlign:'center'}}><div style={{fontSize:40}}>🛡️</div><h2 style={{color:C.navy}}>Member access required</h2><p style={{color:C.muted,fontSize:13,maxWidth:520,margin:'0 auto'}}>{pending?'Your request is awaiting moderator approval. The community feed will unlock after approval.':'Join this community to view its discussions and events.'}</p></div>:
      <div className="hc-community-layout" style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) 300px',gap:18,alignItems:'start'}}><section>
        <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10,marginBottom:12,flexWrap:'wrap'}}><div><h2 style={{fontSize:18,margin:0}}>Community feed</h2><div style={{fontSize:11,color:C.muted,marginTop:3}}>Posts are shown from the live HealthConnect database.</div></div><select value={sort} onChange={e=>setSort(e.target.value as any)} style={{...input,width:'auto'}}><option value="newest">Newest</option><option value="popular">Popular</option></select></div>
        {feedLoading?<div style={emptySmall}>Loading feed…</div>:posts.length===0?<div style={emptySmall}>No published posts yet.{joined?' Be the first to start a discussion.':''}</div>:<div style={{display:'grid',gap:12}}>{posts.map(post=>{
          const ownReactions=post.userReactions||[];return <article key={post.id} style={{...panel,borderLeft:post.isPinned?`4px solid ${C.teal}`:`1px solid ${C.border}`}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{display:'flex',gap:7,alignItems:'center',flexWrap:'wrap'}}><b style={{fontSize:12.5,color:C.navy}}>{post.author_name||'HealthConnect Member'}</b>{post.is_doctor&&<span style={{...pill,background:'#EFF6FF',color:C.blue}}>✓ Verified doctor</span>}{post.isPinned&&<span style={pill}>Pinned</span>}</div><div style={{fontSize:10.5,color:C.muted,marginTop:3}}>{ago(post.createdAt)}</div></div><div style={{display:'flex',gap:5}}>{post.is_doctor&&post.author?.doctorId&&<button onClick={()=>router.push(`/doctors/${post.author.doctorId}`)} style={miniBtn}>Doctor profile</button>}{canModerate&&<button disabled={busyPost===post.id} onClick={()=>pin(post)} style={miniBtn}>{post.isPinned?'Unpin':'Pin'}</button>}{(post.isMine||canModerate)&&<button disabled={busyPost===post.id} onClick={()=>removePost(post)} style={{...miniBtn,color:C.red}}>Remove</button>}</div></div>{post.title&&<h3 style={{fontSize:16.5,margin:'12px 0 6px',color:C.navy}}>{post.title}</h3>}<p style={{fontSize:13,lineHeight:1.68,color:C.text,whiteSpace:'pre-wrap',margin:'8px 0'}}>{post.body}</p>{post.tags?.length>0&&<div style={{display:'flex',gap:5,flexWrap:'wrap',marginTop:9}}>{post.tags.map((tag:string)=><span key={tag} style={{...pill,background:'#F4F6F9',color:C.muted}}>#{tag}</span>)}</div>}<div style={{display:'flex',gap:7,alignItems:'center',flexWrap:'wrap',borderTop:`1px solid ${C.border}`,paddingTop:11,marginTop:12}}>{reactions.map(([type,icon,label])=><button key={type} disabled={busyPost===post.id} onClick={()=>react(post,type)} style={{...reactionBtn,background:ownReactions.includes(type.toLowerCase())?C.tealSoft:'#fff',color:ownReactions.includes(type.toLowerCase())?C.tealDark:C.text}}>{icon} {label} {post.reactions?.[type.toLowerCase()]||0}</button>)}<button onClick={()=>setCommentPost(post)} style={reactionBtn}>💬 Replies {post.comment_count||0}</button>{joined&&<button onClick={()=>report(post)} style={{...reactionBtn,marginLeft:'auto'}}>⚑ Report</button>}</div></article>;
        })}</div>}
      </section>
      <aside style={{display:'grid',gap:12}}>{health&&<div style={panel}><div style={sideTitle}>Community health</div><div style={{display:'flex',alignItems:'baseline',gap:8}}><b style={{fontSize:28,color:C.tealDark}}>{health.score}</b><span style={{fontSize:12,color:C.muted}}>/ 100 · {health.grade}</span></div><div style={{fontSize:11,color:C.muted,marginTop:6}}>{health.postsLast30Days} posts · {health.commentsLast30Days} replies in 30 days</div></div>}{community.rules&&<div style={panel}><div style={sideTitle}>Community rules</div><p style={{fontSize:11.8,lineHeight:1.6,color:C.text,margin:0,whiteSpace:'pre-wrap'}}>{community.rules}</p></div>}<div style={panel}><div style={sideTitle}>Upcoming events</div>{events.length===0?<div style={{fontSize:11.5,color:C.muted}}>No upcoming events.</div>:events.slice(0,5).map(event=><div key={event.id} style={{borderTop:`1px solid ${C.border}`,padding:'10px 0'}}><b style={{fontSize:12,color:C.navy}}>{event.title}</b><div style={{fontSize:10.5,color:C.muted,marginTop:3}}>{dateTime(event.eventDate)}</div>{joined&&<div style={{display:'flex',gap:5,marginTop:7}}><button onClick={()=>rsvp(event,'GOING')} style={{...miniBtn,color:event.myRsvp==='GOING'?C.tealDark:C.text}}>Going</button><button onClick={()=>rsvp(event,'MAYBE')} style={miniBtn}>Maybe</button></div>}</div>)}</div>{canModerate&&<div style={panel}><div style={sideTitle}>Moderator tools</div><button onClick={loadReports} style={{...secondary,width:'100%'}}>Open reports queue</button></div>}</aside></div>}
    </div>
  </main>{createOpen&&<CreatePost community={community} onClose={()=>setCreateOpen(false)} onCreated={async()=>{setCreateOpen(false);await loadCommunity();await loadFeed(community);setNotice('Post published.');}}/>}{commentPost&&<CommentDrawer post={commentPost} onClose={()=>setCommentPost(null)} canWrite={joined||user?.role==='ADMIN'} allowAnonymous={community.allowAnonymous} onCountChanged={n=>setPosts(prev=>prev.map(p=>p.id===commentPost.id?{...p,comment_count:n}:p))}/>} {showModeration&&<div style={overlay} onMouseDown={e=>{if(e.target===e.currentTarget)setShowModeration(false)}}><div style={{width:'min(680px,96vw)',maxHeight:'85vh',overflowY:'auto',background:'#fff',borderRadius:20,padding:22}}><div style={{display:'flex',justifyContent:'space-between'}}><h2 style={{margin:0,fontSize:18}}>Moderation queue</h2><button onClick={()=>setShowModeration(false)} style={iconButton}>×</button></div>{reports.length===0?<div style={emptySmall}>No pending reports.</div>:<div style={{display:'grid',gap:9,marginTop:14}}>{reports.map(r=><div key={r.id} style={{border:`1px solid ${C.border}`,borderRadius:12,padding:12}}><div style={{fontSize:11,color:C.muted}}>{r.targetType} · {r.reason}</div><div style={{fontSize:12.5,color:C.text,margin:'6px 0'}}>{r.details||'No additional details.'}</div><div style={{display:'flex',gap:7}}><button onClick={()=>resolve(r,'DISMISS')} style={secondary}>Dismiss</button><button onClick={()=>resolve(r,'DELETE_CONTENT')} style={{...primary,background:C.red}}>Remove content</button></div></div>)}</div>}</div></div>}
    <style>{`@media(max-width:850px){.hc-community-layout{grid-template-columns:1fr!important}}`}</style></div>;
}

const panel:React.CSSProperties={background:C.card,border:`1px solid ${C.border}`,borderRadius:16,padding:16,boxShadow:'0 2px 10px rgba(15,31,56,.04)'};
const primary:React.CSSProperties={border:0,borderRadius:9,padding:'9px 13px',background:`linear-gradient(135deg,${C.tealDark},${C.teal})`,color:'#fff',fontSize:12,fontWeight:800,cursor:'pointer',fontFamily:'inherit'};
const secondary:React.CSSProperties={border:`1px solid ${C.border}`,borderRadius:9,padding:'8px 12px',background:'#fff',color:C.text,fontSize:12,fontWeight:750,cursor:'pointer',fontFamily:'inherit'};
const input:React.CSSProperties={boxSizing:'border-box',border:`1px solid ${C.border}`,borderRadius:9,padding:'8px 10px',fontSize:12,color:C.navy,background:'#fff',fontFamily:'inherit'};
const textarea:React.CSSProperties={width:'100%',boxSizing:'border-box',border:`1px solid ${C.border}`,borderRadius:10,padding:'10px 11px',fontSize:12.5,color:C.navy,fontFamily:'inherit',resize:'vertical'};
const pill:React.CSSProperties={borderRadius:999,padding:'3px 7px',fontSize:9.5,fontWeight:800,background:C.tealSoft,color:C.tealDark};
const miniBtn:React.CSSProperties={border:`1px solid ${C.border}`,background:'#fff',color:C.text,borderRadius:7,padding:'5px 7px',fontSize:10.5,fontWeight:700,cursor:'pointer'};
const reactionBtn:React.CSSProperties={border:`1px solid ${C.border}`,background:'#fff',color:C.text,borderRadius:8,padding:'6px 8px',fontSize:10.5,fontWeight:700,cursor:'pointer'};
const sideTitle:React.CSSProperties={fontSize:11,fontWeight:850,letterSpacing:'.08em',textTransform:'uppercase',color:C.muted,marginBottom:10};
const overlay:React.CSSProperties={position:'fixed',inset:0,zIndex:2200,background:'rgba(15,31,56,.48)',display:'grid',placeItems:'center',padding:18};
const iconButton:React.CSSProperties={width:34,height:34,borderRadius:9,border:`1px solid ${C.border}`,background:'#F8FAFC',cursor:'pointer',fontSize:20,color:C.text};
const errorBox:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:12,background:'#FFF5F5',border:'1px solid #FECACA',color:C.red,borderRadius:11,padding:'10px 13px',fontSize:12,marginBottom:12};
const noticeBox:React.CSSProperties={display:'flex',justifyContent:'space-between',gap:12,background:C.tealSoft,border:'1px solid #B8EEE6',color:C.tealDark,borderRadius:11,padding:'10px 13px',fontSize:12,marginBottom:12};
const plainX:React.CSSProperties={background:'none',border:0,color:'currentColor',fontWeight:900,cursor:'pointer'};
const emptySmall:React.CSSProperties={background:'#fff',border:`1px dashed ${C.border}`,borderRadius:13,padding:'25px 16px',textAlign:'center',fontSize:12,color:C.muted,marginTop:12};
const centerPage:React.CSSProperties={minHeight:'100vh',display:'grid',placeItems:'center',background:C.page,color:C.text,fontFamily:"'Inter',system-ui,sans-serif"};
