export const CONSTANTS = {
  // Registration ID prefixes
  REGISTRATION_PREFIX: {
    PATIENT: 'HCP',
    DOCTOR: 'HCD',
    HOSPITAL: 'HCH',
  },
  
  // Pagination defaults
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },
  
  // File upload limits
  FILE_UPLOAD: {
    MAX_SIZE: 20 * 1024 * 1024, // 20MB
    ALLOWED_TYPES: ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'],
  },
  
  // Health score weights
  HEALTH_SCORE: {
    MEDICATION_ADHERENCE_WEIGHT: 0.30,
    SYMPTOM_FREQUENCY_WEIGHT: 0.25,
    APPOINTMENT_REGULARITY_WEIGHT: 0.25,
    LIFESTYLE_FACTORS_WEIGHT: 0.20,
  },
  
  // Consent defaults
  CONSENT: {
    DEFAULT_EXPIRY_DAYS: 30,
    MAX_EXPIRY_DAYS: 365,
  },
  
  // Appointment slots
  APPOINTMENT: {
    DEFAULT_DURATION: 30, // minutes
    MIN_ADVANCE_BOOKING_HOURS: 2,
    MAX_ADVANCE_BOOKING_DAYS: 60,
  },
};

export const ERROR_CODES = {
  // Auth errors
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  
  // Validation errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_INPUT: 'INVALID_INPUT',
  
  // Resource errors
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  
  // Business logic errors
  INVALID_ROLE: 'INVALID_ROLE',
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  CONSENT_EXPIRED: 'CONSENT_EXPIRED',
  SLOT_NOT_AVAILABLE: 'SLOT_NOT_AVAILABLE',
  APPOINTMENT_CONFLICT: 'APPOINTMENT_CONFLICT',
  
  // Server errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
};
