'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { api, patientAPI } from '@/lib/api';
import { useUIStore } from '@/store/uiStore';

type Domain = { key:string; label:string; weight:number; score:number|null; status:string; confidence:number; latestValue?:string|null; explanation:string; source:string };
type Alert = { severity:'INFO'|'WARNING'|'CRITICAL'; code:string; title:string; message:string; observedAt?:string|null };
type HealthScore = { score:number|null; status:string; confidence:number; dataCoverage:number; algorithmVersion:string; trend:string; delta:number|null; domains:Domain[]; alerts:Alert[]; missingData:Array<{key:string;label:string;reason:string}>; recommendations:string[]; history:Array<{score:number|null;confidence:number;algorithmVersion:string;date:string}> };
type Lifestyle = { heightCm:number|null; waistCm:number|null; moderateActivityMinWeek:number|null; vigorousActivityMinWeek:number|null; sleepHoursAvg:number|null; tobaccoStatus:string|null; fruitVegServingsDay:number|null };

const C={card:'#fff',border:'#DCE8F2',text:'#0F2742',text2:'#385672',text3:'#6D859B',blue:'#1A6BB5',green:'#15803D',amber:'#B45309',red:'#BE123C',purple:'#6D28D9'};
const META:Record<string,{label:string;color:string;bg:string}>={STRONG:{label:'Strong',color:C.green,bg:'#ECFDF3'},GOOD:{label:'Good / Monitor',color:C.blue,bg:'#EDF6FD'},NEEDS_ATTENTION:{label:'Needs Attention',color:C.amber,bg:'#FFF7ED'},NEEDS_REVIEW:{label:'Needs Review',color:C.red,bg:'#FFF1F2'},INSUFFICIENT_DATA:{label:'Insufficient Data',color:'#64748B',bg:'#F1F5F9'},NO_DATA:{label:'No Data',color:'#64748B',bg:'#F1F5F9'}};
const unwrap=<T,>(r:any):T=>(r?.data?.data??r?.data??{}) as T;
const scoreColor=(n:number|null)=>n==null?'#64748B':n>=85?C.green:n>=70?C.blue:n>=55?C.amber:C.red;

function Ring({score}:{score:number|null}){const v=score??0,c=2*Math.PI*50,o=c-(v/100)*c;return <div style={{position:'relative',width:128,height:128}}><svg width="128" height="128" viewBox="0 0 128 128" style={{transform:'rotate(-90deg)'}}><circle cx="64" cy="64" r="50" fill="none" stroke="#E8EEF4" strokeWidth="12"/><circle cx="64" cy="64" r="50" fill="none" stroke={scoreColor(score)} strokeWidth="12" strokeLinecap="round" strokeDasharray={c} strokeDashoffset={o}/></svg><div style={{position:'absolute',inset:0,display:'grid',placeItems:'center',alignContent:'center'}}><b style={{fontSize:34,color:scoreColor(score),lineHeight:1}}>{score??'—'}</b><span style={{fontSize:10,color:C.text3}}>/ 100</span></div></div>}

function DomainCard({d}:{d:Domain}){const m=META[d.status]??META.NO_DATA;return <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:15,display:'grid',gap:8}}><div style={{display:'flex',gap:8}}><div style={{flex:1}}><b style={{fontSize:14,color:C.text}}>{d.label}</b><div style={{fontSize:10,color:C.text3,marginTop:3}}>Weight {d.weight}% · Confidence {d.confidence}%</div></div><b style={{fontSize:25,color:scoreColor(d.score)}}>{d.score??'—'}</b></div><span style={{justifySelf:'start',fontSize:10,padding:'2px 8px',borderRadius:99,color:m.color,background:m.bg,fontWeight:800}}>{m.label}</span><div style={{height:6,background:'#EDF2F7',borderRadius:99,overflow:'hidden'}}><div style={{height:'100%',width:`${d.score??0}%`,background:scoreColor(d.score)}}/></div>{d.latestValue&&<div style={{fontSize:12,fontWeight:700,color:C.text2}}>Latest: {d.latestValue}</div>}<div style={{fontSize:12,lineHeight:1.5,color:C.text3}}>{d.explanation}</div><div style={{fontSize:10,color:C.text3}}>Source: {d.source}</div></div>}

function LifestyleForm({afterSave}:{afterSave:()=>Promise<void>}){
  const empty:Lifestyle={heightCm:null,waistCm:null,moderateActivityMinWeek:null,vigorousActivityMinWeek:null,sleepHoursAvg:null,tobaccoStatus:null,fruitVegServingsDay:null};
  const [f,setF]=useState<Lifestyle>(empty),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
  useEffect(()=>{api.get('/patient/health-score/lifestyle').then(r=>setF({...empty,...unwrap<Lifestyle>(r)})).catch(()=>{}).finally(()=>setLoading(false));},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const set=(k:keyof Lifestyle,v:any)=>setF(p=>({...p,[k]:v===''?null:v}));
  const save=async()=>{setSaving(true);setMsg('');try{await api.put('/patient/health-score/lifestyle',f);await afterSave();setMsg('Saved and recalculated.');}catch(e:any){setMsg(e?.response?.data?.message??'Unable to save.');}finally{setSaving(false)}};
  if(loading)return <div style={{fontSize:12,color:C.text3}}>Loading measurable health inputs…</div>;
  const input:React.CSSProperties={width:'100%',padding:'9px 10px',border:`1px solid ${C.border}`,borderRadius:9,background:'#FAFCFE',fontSize:12,color:C.text,boxSizing:'border-box'};
  const num=(label:string,key:keyof Lifestyle,ph:string)=><div><label style={{display:'block',fontSize:10,fontWeight:800,color:C.text3,marginBottom:5,textTransform:'uppercase'}}>{label}</label><input type="number" value={(f[key] as number|null)??''} placeholder={ph} onChange={e=>set(key,e.target.value===''?null:Number(e.target.value))} style={input}/></div>;
  return <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:17}}><div style={{fontSize:14,fontWeight:900,color:C.text}}>Measurable lifestyle inputs</div><div style={{fontSize:11,color:C.text3,margin:'4px 0 13px'}}>These inputs unlock Body Composition, Activity, Sleep and Nutrition/Tobacco scoring. Unknown values remain unscored.</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(155px,1fr))',gap:10}}>{num('Height (cm)','heightCm','165')}{num('Waist (cm)','waistCm','optional')}{num('Moderate activity min/week','moderateActivityMinWeek','150')}{num('Vigorous activity min/week','vigorousActivityMinWeek','60')}{num('Sleep hours/night','sleepHoursAvg','7.5')}{num('Fruit & veg servings/day','fruitVegServingsDay','5')}<div><label style={{display:'block',fontSize:10,fontWeight:800,color:C.text3,marginBottom:5,textTransform:'uppercase'}}>Tobacco exposure</label><select value={f.tobaccoStatus??''} onChange={e=>set('tobaccoStatus',e.target.value)} style={input}><option value="">Not provided</option><option value="NEVER">Never</option><option value="FORMER">Former</option><option value="CURRENT">Current</option><option value="SECONDHAND">Second-hand exposure</option></select></div></div><div style={{display:'flex',gap:10,alignItems:'center',marginTop:12}}><button onClick={save} disabled={saving} style={{padding:'9px 15px',border:0,borderRadius:9,background:C.blue,color:'#fff',fontSize:12,fontWeight:800,cursor:saving?'wait':'pointer',opacity:saving?0.65:1}}>{saving?'Saving…':'Save & recalculate'}</button>{msg&&<span style={{fontSize:11,color:msg.startsWith('Unable')?C.red:C.green}}>{msg}</span>}</div></div>;
}

function History({rows}:{rows:HealthScore['history']}){const v=(rows??[]).filter(x=>x.score!=null).slice(0,8).reverse();if(!v.length)return <div style={{fontSize:12,color:C.text3}}>No saved score snapshots yet.</div>;return <div style={{display:'flex',alignItems:'flex-end',gap:10,height:110,paddingTop:10}}>{v.map((r,i)=><div key={`${r.date}-${i}`} style={{flex:1,height:'100%',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'flex-end',gap:4}}><b style={{fontSize:10,color:scoreColor(r.score)}}>{r.score}</b><div style={{width:28,height:`${Math.max(6,((r.score??0)/100)*70)}px`,background:scoreColor(r.score),borderRadius:'5px 5px 2px 2px'}}/><span style={{fontSize:9,color:C.text3}}>{new Date(r.date).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</span></div>)}</div>}

export default function OverviewTab({loading:parentLoading}:{data?:any;loading?:boolean}){
  const ui=useUIStore() as any;
  const [h,setH]=useState<HealthScore|null>(null),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{setH(unwrap<HealthScore>(await patientAPI.getHealthScore()));}catch(e:any){setError(e?.response?.data?.message??'Unable to load health score.');}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const refresh=async()=>{setRefreshing(true);setError('');try{setH(unwrap<HealthScore>(await patientAPI.refreshHealthScore()));}catch(e:any){setError(e?.response?.data?.message??'Unable to recalculate health score.');throw e;}finally{setRefreshing(false)}};
  const critical=useMemo(()=>h?.alerts?.filter(a=>a.severity==='CRITICAL')??[],[h]); const warnings=useMemo(()=>h?.alerts?.filter(a=>a.severity==='WARNING')??[],[h]); const meta=META[h?.status??'INSUFFICIENT_DATA'];
  if(loading||parentLoading)return <div style={{height:420,borderRadius:16,background:'#EDF3F8'}}/>;
  return <div style={{display:'grid',gap:18}}>
    {error&&<div style={{padding:'11px 14px',border:'1px solid #FECDD3',background:'#FFF1F2',borderRadius:12,color:C.red,fontSize:12}}>{error}</div>}
    {critical.map(a=><div key={`${a.code}-${a.observedAt}`} style={{padding:15,border:'1.5px solid #FDA4AF',background:'#FFF1F2',borderRadius:14}}><b style={{color:C.red}}>⚠ {a.title}</b><div style={{fontSize:12,color:'#7F1D1D',lineHeight:1.55,marginTop:5}}>{a.message}</div><div style={{fontSize:10,color:'#9F1239',marginTop:5}}>Do not use the overall score to dismiss this alert.</div></div>)}
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:18,padding:21}}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><div style={{fontSize:11,fontWeight:800,color:C.text3,textTransform:'uppercase',letterSpacing:'.07em'}}>HealthConnect Health Status Index</div><h2 style={{fontSize:22,color:C.text,margin:'4px 0'}}>Your Health Score</h2><div style={{fontSize:11,color:C.text3}}>Algorithm {h?.algorithmVersion??'HC-HSI-1.0'} · decision support, not a diagnosis</div></div><button onClick={refresh} disabled={refreshing} style={{height:36,padding:'0 14px',border:`1px solid ${C.border}`,borderRadius:9,background:'#fff',color:C.blue,fontWeight:800,fontSize:12,cursor:refreshing?'wait':'pointer'}}>{refreshing?'Recalculating…':'↻ Recalculate & save'}</button></div><div style={{display:'grid',gridTemplateColumns:'145px 1fr',gap:22,alignItems:'center',marginTop:18}}><Ring score={h?.score??null}/><div><span style={{display:'inline-block',padding:'4px 10px',borderRadius:99,background:meta.bg,color:meta.color,fontSize:11,fontWeight:900}}>{meta.label}</span><p style={{fontSize:13,lineHeight:1.6,color:C.text2}}>{h?.score==null?'There is not enough reliable structured data to calculate a responsible score. Missing data is never counted as healthy.':'Only measured domains contribute to the score. Missing domains contribute neither good nor bad points; confidence reflects completeness and freshness.'}</p><div style={{display:'flex',justifyContent:'space-between',fontSize:11,color:C.text3,marginBottom:5}}><b>Data confidence</b><span>{h?.confidence??0}% · coverage {h?.dataCoverage??0}%</span></div><div style={{height:8,background:'#E8EEF4',borderRadius:99,overflow:'hidden'}}><div style={{height:'100%',width:`${h?.confidence??0}%`,background:(h?.confidence??0)>=70?C.green:(h?.confidence??0)>=40?C.blue:C.amber}}/></div></div></div></div>
    {warnings.length>0&&<div style={{padding:15,border:'1px solid #FED7AA',background:'#FFF7ED',borderRadius:14}}><b style={{color:C.amber,fontSize:13}}>Health alerts</b>{warnings.map(a=><div key={`${a.code}-${a.observedAt}`} style={{fontSize:12,color:'#7C2D12',lineHeight:1.5,marginTop:6}}><strong>{a.title}:</strong> {a.message}</div>)}</div>}
    <div><h3 style={{margin:'0 0 3px',fontSize:16,color:C.text}}>Health domains</h3><div style={{fontSize:11,color:C.text3,marginBottom:10}}>Ten weighted domains with explicit no-data handling.</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(285px,1fr))',gap:12}}>{(h?.domains??[]).map(d=><DomainCard key={d.key} d={d}/>)}</div></div>
    <LifestyleForm afterSave={refresh}/>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:14}}><div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:16}}><b style={{fontSize:13,color:C.text}}>What to focus on</b>{!h?.recommendations?.length?<div style={{fontSize:12,color:C.text3,marginTop:8}}>No recommendations yet.</div>:h.recommendations.map((r,i)=><div key={i} style={{fontSize:12,color:C.text2,lineHeight:1.5,marginTop:7}}><b style={{color:C.blue}}>{i+1}.</b> {r}</div>)}</div><div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:16}}><b style={{fontSize:13,color:C.text}}>Missing data</b><div style={{display:'flex',flexWrap:'wrap',gap:6,marginTop:9}}>{!h?.missingData?.length?<span style={{fontSize:12,color:C.green}}>All v1 domains have usable data.</span>:h.missingData.map(m=><span key={m.key} title={m.reason} style={{fontSize:10,fontWeight:700,color:C.text3,background:'#F1F5F9',padding:'5px 8px',borderRadius:99}}>{m.label}</span>)}</div></div></div>
    <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:16}}><div style={{display:'flex',justifyContent:'space-between'}}><div><b style={{fontSize:13,color:C.text}}>Versioned history</b><div style={{fontSize:10,color:C.text3,marginTop:3}}>Compare snapshots within the same algorithm version.</div></div><span style={{fontSize:10,color:C.purple,fontWeight:800}}>{h?.algorithmVersion}</span></div><History rows={h?.history??[]}/></div>
    <div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{[['vitals','Log vitals'],['medications','Medication adherence'],['symptoms','Track symptoms']].map(([p,l])=><button key={p} onClick={()=>ui.setActivePage(p)} style={{padding:'8px 12px',border:`1px solid ${C.border}`,borderRadius:9,background:'#fff',color:C.blue,fontSize:11,fontWeight:800,cursor:'pointer'}}>{l}</button>)}</div>
  </div>;
}
