'use client';
import { useState, useEffect, useCallback } from 'react';
import { patientAPI } from '@/lib/api';
import { useUIStore } from '@/store/uiStore';
import { useAuthStore } from '@/store/authStore';
import ProfileOnboardingModal, { isOnboardingDone, isOnboardingSnoozed } from '@/components/onboarding/ProfileOnboardingModal';
import { ProfileCompletenessBanner, useProfileScore } from '@/components/onboarding/ProfileCompleteness';

const C={border:'#C8DFF0',text:'#0D1F3C',text2:'#2C4A6E',text3:'#5A7A9B',green:'#15803D',amber:'#B45309',rose:'#BE123C',violet:'#5B21B6'};
function scoreColor(s:number){return s>=85?'#15803D':s>=70?'#1A6BB5':s>=55?'#B45309':'#BE123C'}
function KpiCard({icon,label,value,sub,color,onClick}:any){return <div onClick={onClick} style={{background:'#FDFCFB',border:'1px solid #E8E6DF',borderRadius:14,padding:'20px 22px',cursor:onClick?'pointer':'default',boxShadow:'0 1px 4px rgba(0,0,0,.05)'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:12}}><span style={{fontSize:22}}>{icon}</span>{sub&&<span style={{fontSize:10.5,color:'#64748B',background:'#F1F0EB',padding:'2px 7px',borderRadius:100,border:'1px solid #E8E6DF'}}>{sub}</span>}</div><div style={{fontSize:28,fontWeight:800,color:color??'#1A6BB5',lineHeight:1,marginBottom:4}}>{value}</div><div style={{fontSize:12,color:'#2C4A6E',fontWeight:500}}>{label}</div></div>}

export default function HomePage(){
 const uiStore=useUIStore() as any;const user=(useAuthStore.getState() as any).user;
 const [data,setData]=useState<any>(null),[fullProfile,setFullProfile]=useState<any>(null),[health,setHealth]=useState<any>(null),[loading,setLoading]=useState(true),[showOnboarding,setShowOnboarding]=useState(false);
 const {score:profileScore,sections:profileSections}=useProfileScore(fullProfile??data?.profile??{},'PATIENT');
 useEffect(()=>{if(user&&!isOnboardingDone()&&!isOnboardingSnoozed())setShowOnboarding(true)},[user]);
 const firstName=user?.firstName??data?.profile?.firstName??'there';const hour=new Date().getHours();const greeting=hour<12?'Good morning':hour<17?'Good afternoon':'Good evening';const greetEmoji=hour<12?'🌅':hour<17?'👋':'🌙';const today=new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
 const load=useCallback(async()=>{setLoading(true);try{const [dashRes,profRes,healthRes]=await Promise.allSettled([patientAPI.dashboard(),(patientAPI as any).getProfile(),patientAPI.getHealthScore()]);if(dashRes.status==='fulfilled')setData((dashRes.value as any)?.data?.data??(dashRes.value as any)?.data??{});if(profRes.status==='fulfilled')setFullProfile((profRes.value as any)?.data?.data??(profRes.value as any)?.data??{});if(healthRes.status==='fulfilled')setHealth((healthRes.value as any)?.data?.data??(healthRes.value as any)?.data??{});}finally{setLoading(false)}},[]);
 useEffect(()=>{load()},[load]);
 const kpis=data?.kpis??{};const healthScore=health?.score??null;const upcomingCount=kpis.upcomingAppointmentsCount??0;const activeMedsCount=kpis.activeMedicationsCount??0;const symptomsCount=kpis.recentSymptomsCount??0;const refillCount=kpis.refillAlertsCount??0;const adherencePct=kpis.medicationAdherencePct??0;const nextAppt=data?.upcomingAppointments?.[0]??null;const activeMeds=data?.activeMedications??[];const recentVitals=data?.recentVitals??[];const recentSymptoms=data?.recentSymptoms??[];
 const QUICK_ACTIONS=[{icon:'🎯',label:healthScore==null?'Start Health Score':'View Health Score',page:'my-health'},{icon:'📊',label:'Log Vitals',page:'vitals'},{icon:'🤒',label:'Log Symptom',page:'symptoms'},{icon:'📁',label:'Upload Report',page:'my-health'},{icon:'💊',label:'My Medications',page:'medications'},{icon:'👩‍⚕️',label:'Find Doctors',page:'find-doctors'}];
 return <>{showOnboarding&&<ProfileOnboardingModal role="PATIENT" userName={user?.firstName} onClose={()=>setShowOnboarding(false)}/>}<style>{`.hp-skel{border-radius:12px;background:linear-gradient(90deg,#E8E6DF 25%,#EFEDE6 50%,#E8E6DF 75%);background-size:200% 100%;animation:hp-sh 1.5s infinite}@keyframes hp-sh{0%{background-position:200% 0}100%{background-position:-200% 0}}.hp-qa{display:flex;flex-direction:column;align-items:center;gap:8px;padding:16px 10px;background:#FDFCFB;border:1px solid #E8E6DF;border-radius:14px;cursor:pointer;transition:.2s}.hp-qa:hover{transform:translateY(-2px);box-shadow:0 4px 12px rgba(0,0,0,.08)}@media(max-width:900px){.hp-kpis,.hp-two,.hp-qa-grid{grid-template-columns:1fr!important}}`}</style><div style={{maxWidth:1100}}>
 <div style={{background:'#FDFCFB',borderRadius:16,padding:'24px 28px',marginBottom:20,boxShadow:'0 2px 8px rgba(0,0,0,.06)',border:'1px solid #E8E6DF'}}><h1 style={{color:'#1E293B',fontSize:22,fontWeight:800,margin:'0 0 5px'}}>{greeting}, {firstName} {greetEmoji}</h1><p style={{color:'#94A3B8',fontSize:12,margin:0}}>{today}</p></div>
 {refillCount>0&&<div onClick={()=>uiStore.setActivePage('medications')} style={{background:'rgba(245,158,11,.08)',border:'1px solid rgba(245,158,11,.25)',borderRadius:12,padding:'12px 18px',marginBottom:16,cursor:'pointer',color:'#B45309',fontSize:13,fontWeight:700}}>⚠️ {refillCount} medication{refillCount>1?'s':''} need refill <span style={{float:'right'}}>View →</span></div>}
 <ProfileCompletenessBanner score={profileScore} role="PATIENT" sections={profileSections} onGoToProfile={()=>uiStore.setActivePage('profile')}/>
 <div className="hp-kpis" style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:14,marginBottom:24}}>{loading?[1,2,3,4].map(i=><div key={i} className="hp-skel" style={{height:110}}/>):<><KpiCard icon="🎯" label="Health Score" value={healthScore??'—'} color={healthScore==null?'#1A6BB5':scoreColor(healthScore)} onClick={()=>uiStore.setActivePage('my-health')}/><KpiCard icon="💊" label="Active Medications" value={activeMedsCount} sub={refillCount>0?`${refillCount} refill needed`:'Current list'} color="#1A6BB5" onClick={()=>uiStore.setActivePage('medications')}/><KpiCard icon="📅" label="Upcoming Appointments" value={upcomingCount} sub="Scheduled" color={C.violet} onClick={()=>uiStore.setActivePage('appointments')}/><KpiCard icon="🤒" label="Symptoms This Week" value={symptomsCount} sub="Logged" color={symptomsCount>3?C.rose:C.green} onClick={()=>uiStore.setActivePage('symptoms')}/></>}</div>
 <div className="hp-two" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20,marginBottom:24}}><div style={{background:'#FDFCFB',border:'1px solid #E8E6DF',borderRadius:14,padding:'16px 18px'}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><b>📅 NEXT APPOINTMENT</b><button onClick={()=>uiStore.setActivePage('appointments')} style={{border:0,background:'none',cursor:'pointer'}}>View all →</button></div>{nextAppt?<div><b>Dr. {nextAppt.doctor?.firstName} {nextAppt.doctor?.lastName}</b><div style={{fontSize:12,color:C.text3,marginTop:5}}>{new Date(nextAppt.scheduledAt).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})} · {nextAppt.type}</div></div>:<div style={{padding:'22px 0',textAlign:'center',color:C.text3}}>No upcoming appointments</div>}</div><div style={{background:'#FDFCFB',border:'1px solid #E8E6DF',borderRadius:14,padding:'16px 18px'}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:12}}><b>💊 TODAY'S MEDICATIONS</b><button onClick={()=>uiStore.setActivePage('medications')} style={{border:0,background:'none',cursor:'pointer'}}>View all →</button></div>{activeMeds.length?<><div style={{fontSize:12,color:C.text3,marginBottom:9}}>{adherencePct}% logged adherence</div>{activeMeds.slice(0,4).map((m:any)=><div key={m.id} style={{padding:'8px 10px',background:'#F5F4F0',borderRadius:9,marginBottom:6,fontSize:12}}><b>{m.name}</b> <span style={{color:C.text3}}>{m.dosage}</span></div>)}</>:<div style={{padding:'22px 0',textAlign:'center',color:C.text3}}>No active medications recorded</div>}</div></div>
 <div style={{background:'#FDFCFB',border:'1px solid #E8E6DF',borderRadius:14,padding:'20px 22px',marginBottom:24}}><b style={{fontSize:13}}>⚡ QUICK ACTIONS</b><div className="hp-qa-grid" style={{display:'grid',gridTemplateColumns:'repeat(6,1fr)',gap:10,marginTop:12}}>{QUICK_ACTIONS.map(a=><button key={`${a.page}-${a.label}`} className="hp-qa" onClick={()=>uiStore.setActivePage(a.page)}><span style={{fontSize:24}}>{a.icon}</span><span style={{fontSize:11,color:C.text2,fontWeight:650,textAlign:'center'}}>{a.label}</span></button>)}</div></div>
 <div className="hp-two" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}><div style={{background:'#FDFCFB',border:'1px solid #E8E6DF',borderRadius:14,padding:'16px 18px'}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:10}}><b>📊 RECENT VITALS</b><button onClick={()=>uiStore.setActivePage('vitals')} style={{border:0,background:'none',cursor:'pointer'}}>Log →</button></div>{recentVitals.length?<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}>{recentVitals.slice(0,6).map((v:any,i:number)=><div key={v.id??i} style={{background:'#F5F4F0',borderRadius:9,padding:'9px 10px'}}><div style={{fontSize:10,color:C.text3,textTransform:'uppercase'}}>{String(v.type??'').replace(/_/g,' ')}</div><b style={{fontSize:17,color:'#1A6BB5'}}>{v.type==='bp'||v.type==='BLOOD_PRESSURE'?`${v.systolic}/${v.diastolic}`:v.value??'—'} <span style={{fontSize:9,color:C.text3}}>{v.unit}</span></b></div>)}</div>:<div style={{padding:'20px 0',textAlign:'center',color:C.text3}}>No vitals logged yet</div>}</div><div style={{background:'#FDFCFB',border:'1px solid #E8E6DF',borderRadius:14,padding:'16px 18px'}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:10}}><b>🤒 RECENT SYMPTOMS</b><button onClick={()=>uiStore.setActivePage('symptoms')} style={{border:0,background:'none',cursor:'pointer'}}>Log →</button></div>{recentSymptoms.length?recentSymptoms.slice(0,5).map((s:any,i:number)=><div key={s.id??i} style={{padding:'8px 10px',background:'#F5F4F0',borderRadius:9,marginBottom:6,fontSize:12}}><b>{s.name}</b><span style={{float:'right',color:s.severity>=4?C.rose:s.severity>=3?C.amber:C.green}}>{s.severity}/5</span></div>):<div style={{padding:'20px 0',textAlign:'center',color:C.text3}}>No symptoms logged this week</div>}</div></div>
 </div></>;
}
