'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '@/store/authStore';
import { useUIStore } from '@/store/uiStore';

type PathItem={title:string;kicker:string;desc:string;points:string[];href?:string;action:string;color:string;wash:string;kind:'health'|'doctor'|'hospital'|'community'|'knowledge'|'practice'};

const PATHS:PathItem[]=[
  {title:'My Health',kicker:'FOR PATIENTS',desc:'Your private place for the health information you need across visits.',points:['Reports & prescriptions','Medicines, symptoms & vitals','Appointments & follow-ups'],action:'Explore My Health',color:'#0B8F7C',wash:'#EAF8F4',kind:'health'},
  {title:'Find Doctors',kicker:'CARE DISCOVERY',desc:'Find the right doctor with more context before you book.',points:['Specialty & location search','Profiles & consultation options','Availability into booking'],href:'/doctors',action:'Find Doctors',color:'#2563EB',wash:'#EDF4FF',kind:'doctor'},
  {title:'Find Hospitals',kicker:'KNOW BEFORE YOU GO',desc:'Compare hospitals before deciding where to travel for care.',points:['Departments & facilities','Hospital OPD information','Affiliated doctors'],href:'/hospitals',action:'Find Hospitals',color:'#EA580C',wash:'#FFF3E9',kind:'hospital'},
  {title:'Health Communities',kicker:'BETWEEN VISITS',desc:'Condition-focused peer support that continues between appointments.',points:['Shared lived experience','Practical questions & support','Moderated participation'],href:'/communities',action:'Explore Communities',color:'#7C3AED',wash:'#F4EEFF',kind:'community'},
  {title:'Knowledge Hub',kicker:'LEARN & PREPARE',desc:'India-focused explainers for better health conversations.',points:['Condition explainers','Everyday health learning','Prepare better questions'],href:'/learn',action:'Visit Knowledge Hub',color:'#0284C7',wash:'#ECF7FD',kind:'knowledge'},
  {title:'Doctor Platform',kicker:'FOR DOCTORS',desc:'A connected professional workspace for patient care and practice.',points:['My Patients','Practice & schedules','Consultations & follow-up'],action:'Explore Doctor Platform',color:'#0F766E',wash:'#E9F7F4',kind:'practice'},
];

function PathIcon({kind}:{kind:PathItem['kind']}){const map={health:'♡',doctor:'♙',hospital:'▥',community:'◎',knowledge:'▤',practice:'▣'} as const;return <span>{map[kind]}</span>;}

export default function AudienceJourneys(){
  const router=useRouter();
  const {user,isAuthenticated}=useAuthStore();
  const {openAuthModal}=useUIStore();
  const openPatient=()=>{if(!isAuthenticated||!user){try{sessionStorage.setItem('hc_post_login_redirect','/dashboard')}catch{};openAuthModal('login');return;}const role=String(user.role||'').toUpperCase();router.push(role==='PATIENT'?'/dashboard':role==='DOCTOR'?'/doctor-dashboard':role==='HOSPITAL'?'/hospital-dashboard':'/admin-dashboard');};
  const openDoctor=()=>{if(isAuthenticated&&user){const role=String(user.role||'').toUpperCase();router.push(role==='DOCTOR'?'/doctor-dashboard':role==='PATIENT'?'/dashboard':role==='HOSPITAL'?'/hospital-dashboard':'/admin-dashboard');return;}try{sessionStorage.setItem('hc_signup_role','DOCTOR')}catch{};openAuthModal('register');};
  const act=(item:PathItem)=>{if(item.href){router.push(item.href);return;}if(item.kind==='health')openPatient();else openDoctor();};

  return <section className="ap-root" id="platform-tour"><style>{`
    .ap-root{font-family:'DM Sans',Arial,sans-serif;color:#10243C;background:#fff}.ap-overview{padding:70px 28px 78px;background:#fff}.ap-inner{max-width:1340px;margin:0 auto}.ap-intro{text-align:center;max-width:790px;margin:0 auto 32px}.ap-kicker{font-size:12px;font-weight:900;letter-spacing:.18em;text-transform:uppercase;color:#0B8F7C;margin-bottom:10px}.ap-intro h2,.ap-section h2{font-family:'Sora','DM Sans',sans-serif;color:#0B1F36;letter-spacing:-.045em;margin:0}.ap-intro h2{font-size:clamp(2rem,3vw,3.25rem);line-height:1.06}.ap-intro p{font-size:14.5px;line-height:1.6;color:#5A7184;margin:12px auto 0;max-width:700px}.ap-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.ap-card{border:1px solid #DDE8EA;border-radius:18px;padding:21px;min-height:246px;display:flex;flex-direction:column;box-shadow:0 8px 24px rgba(15,55,70,.045)}.ap-card-head{display:flex;align-items:center;gap:12px}.ap-icon{width:44px;height:44px;border-radius:13px;display:grid;place-items:center;font-size:25px;font-weight:800}.ap-card-kicker{font-size:8.5px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;margin-bottom:3px}.ap-card h3{font-family:'Sora','DM Sans',sans-serif;font-size:18px;line-height:1.2;margin:0;color:#10243C}.ap-card>p{font-size:12.25px;line-height:1.55;color:#5E7385;margin:14px 0 12px;max-width:355px}.ap-list{display:grid;gap:6px;margin-bottom:15px}.ap-list span{font-size:10.25px;color:#486275;display:flex;gap:7px;align-items:flex-start}.ap-list span:before{content:'✓';font-weight:900}.ap-link{margin-top:auto;border:0;background:transparent;padding:0;align-self:flex-start;font:900 10.5px 'DM Sans',Arial,sans-serif;cursor:pointer}
    .ap-section{padding:86px 28px}.ap-section .ap-inner{display:grid;grid-template-columns:minmax(410px,.94fr) minmax(0,1.06fr);gap:72px;align-items:center}.ap-section.reverse .ap-inner{grid-template-columns:minmax(0,1.06fr) minmax(410px,.94fr)}.ap-section.reverse .ap-visual{order:2}.ap-section.reverse .ap-copy{order:1}.ap-section .ap-kicker{text-align:left}.ap-section h2{font-size:clamp(2.25rem,3.3vw,3.6rem);line-height:1.04;max-width:650px}.ap-copy>p{font-size:14.5px;line-height:1.68;color:#587086;max-width:650px;margin:15px 0 22px}.ap-benefits{display:grid;gap:14px}.ap-benefit{display:grid;grid-template-columns:34px 1fr;gap:11px;align-items:start}.ap-num{width:31px;height:31px;border-radius:50%;display:grid;place-items:center;font-size:11px;font-weight:900}.ap-benefit b{display:block;font-size:12.5px;color:#17364C;margin-bottom:2px}.ap-benefit span{display:block;font-size:11px;line-height:1.5;color:#617789}.ap-cta{display:inline-flex;margin-top:23px;border-radius:9px;padding:11px 16px;text-decoration:none;color:#fff;border:0;font:900 11px 'DM Sans',Arial,sans-serif;cursor:pointer}.ap-health{background:#ECF8F4}.ap-care{background:#F4F8FB}.ap-doctor{background:#EAF4F7}.ap-visual{min-height:350px;display:flex;align-items:center;justify-content:center}
    .ap-health-ui{width:min(100%,500px);background:#fff;border:1px solid #CDE0DC;border-radius:22px;padding:23px;box-shadow:0 22px 50px rgba(20,73,68,.10);position:relative}.ap-ui-head{display:flex;justify-content:space-between;align-items:center;padding-bottom:13px;border-bottom:1px solid #E6EFED;color:#567381;font-size:10px}.ap-ui-head b{color:#17364C;font-size:12px}.ap-ui-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:17px 0}.ap-ui-kpi{background:#F3F8F7;border-radius:11px;padding:13px;color:#6C818D;font-size:8.5px}.ap-ui-kpi strong{display:block;color:#0B8F7C;font-size:21px;margin-top:4px}.ap-ui-row{height:36px;background:#F2F6F7;border-radius:9px;margin:7px 0;padding:0 12px;display:flex;align-items:center;justify-content:space-between;color:#5B7181;font-size:9.5px}.ap-phone{position:absolute;right:-22px;bottom:-30px;width:142px;height:250px;border:8px solid #12374A;background:#fff;border-radius:28px;padding:20px 10px 10px;box-shadow:0 15px 32px rgba(15,44,58,.15)}.ap-phone:before{content:'';position:absolute;top:8px;left:50%;transform:translateX(-50%);width:52px;height:5px;border-radius:5px;background:#12374A}.ap-phone b{display:block;font-size:10px;margin-bottom:10px}.ap-phone span{display:block;background:#F2F6F7;border-radius:7px;padding:8px;margin:7px 0;color:#607686;font-size:7.5px}
    .ap-care-head{text-align:center;max-width:810px;margin:0 auto 36px}.ap-care-head .ap-kicker{font-size:17px}.ap-care-head h2{font-size:clamp(2.2rem,3vw,3.35rem);max-width:none}.ap-care-head p{font-size:13.5px;line-height:1.6;color:#60778A;max-width:720px;margin:12px auto 0}.ap-care-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.ap-care-card{background:#fff;border:1px solid #DCE7EA;border-radius:22px;overflow:hidden;box-shadow:0 10px 28px rgba(20,54,70,.06)}.ap-care-photo{height:230px;background-size:cover;background-position:center}.ap-care-body{padding:23px 26px 25px}.ap-care-body .ap-card-kicker{font-size:10px}.ap-care-body h3{font-family:'Sora',sans-serif;font-size:22px;letter-spacing:-.035em;margin:5px 0 9px}.ap-care-body p{font-size:12.25px;line-height:1.55;color:#60768A;margin:0 0 14px}.ap-care-body a{font-size:11px;font-weight:900;text-decoration:none}
    .ap-doctor-photo{width:min(100%,540px);height:340px;border-radius:24px;background:url('/images/doctors-intro.png') center/cover no-repeat,linear-gradient(135deg,#DCEEEF,#F5FBFB);box-shadow:0 18px 45px rgba(19,72,78,.10);border:1px solid #CFE2E4}.ap-doctor-chips{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:20px}.ap-doctor-chip{padding:12px;border-radius:12px;background:rgba(255,255,255,.72);border:1px solid #CFE1E4}.ap-doctor-chip b{display:block;font-size:10.5px;color:#17364C;margin-bottom:3px}.ap-doctor-chip span{font-size:9.25px;color:#60778A;line-height:1.4}
    @media(max-width:960px){.ap-grid{grid-template-columns:1fr 1fr}.ap-section .ap-inner,.ap-section.reverse .ap-inner{grid-template-columns:1fr;gap:40px}.ap-section.reverse .ap-visual,.ap-section.reverse .ap-copy{order:initial}.ap-care-grid{grid-template-columns:1fr}}@media(max-width:620px){.ap-overview,.ap-section{padding:54px 14px}.ap-grid{grid-template-columns:1fr}.ap-card{min-height:0}.ap-intro{text-align:left}.ap-health-ui{padding:18px;margin-right:16px}.ap-phone{right:-10px;width:124px;height:225px}.ap-care-photo{height:200px}.ap-doctor-photo{height:280px}.ap-doctor-chips{grid-template-columns:1fr}}
  `}</style>
  <div className="ap-overview"><div className="ap-inner"><div className="ap-intro"><div className="ap-kicker">Your complete healthcare journey</div><h2>Everything important, connected around the person receiving care.</h2><p>Each HealthConnect module has a clear job. Together they reduce disconnected searching, records, booking and follow-up across the healthcare journey.</p></div><div className="ap-grid">{PATHS.map(item=><article className="ap-card" key={item.title} style={{background:item.wash,borderColor:`${item.color}24`}}><div className="ap-card-head"><span className="ap-icon" style={{background:`${item.color}12`,color:item.color}}><PathIcon kind={item.kind}/></span><div><div className="ap-card-kicker" style={{color:item.color}}>{item.kicker}</div><h3>{item.title}</h3></div></div><p>{item.desc}</p><div className="ap-list">{item.points.map(p=><span key={p}>{p}</span>)}</div><button className="ap-link" style={{color:item.color}} onClick={()=>act(item)}>{item.action} →</button></article>)}</div></div></div>
  <section className="ap-section ap-health"><div className="ap-inner"><div className="ap-visual"><div className="ap-health-ui"><div className="ap-ui-head"><b>My Health</b><span>Your private health workspace</span></div><div className="ap-ui-kpis"><div className="ap-ui-kpi">HEALTH SCORE<strong>82</strong></div><div className="ap-ui-kpi">UPCOMING<strong>2</strong></div><div className="ap-ui-kpi">REPORTS<strong>8</strong></div></div><div className="ap-ui-row"><span>Reports & prescriptions</span><b>8</b></div><div className="ap-ui-row"><span>Medicines & reminders</span><b>5</b></div><div className="ap-ui-row"><span>Symptoms & vitals</span><b>Timeline</b></div><div className="ap-phone"><b>Health timeline</b><span>Prescription added</span><span>Lab report</span><span>Follow-up visit</span><span>Medicine reminder</span></div></div></div><div className="ap-copy"><div className="ap-kicker">For patients & families</div><h2>Your health history shouldn&apos;t start over at every visit.</h2><p>My Health keeps reports, prescriptions, medicines, symptoms, vitals and appointments organised in one authenticated patient workspace.</p><div className="ap-benefits"><div className="ap-benefit"><span className="ap-num" style={{background:'#D1F0E9',color:'#087F70'}}>1</span><div><b>Keep it together</b><span>Carry important health information as one journey instead of scattered records.</span></div></div><div className="ap-benefit"><span className="ap-num" style={{background:'#D1F0E9',color:'#087F70'}}>2</span><div><b>Stay ahead</b><span>Track medicines, reminders, upcoming care and follow-ups in one place.</span></div></div><div className="ap-benefit"><span className="ap-num" style={{background:'#D1F0E9',color:'#087F70'}}>3</span><div><b>Be better prepared</b><span>Bring useful health context into your next conversation with a doctor.</span></div></div></div><button className="ap-cta" style={{background:'#0B8F7C'}} onClick={openPatient}>Explore My Health →</button></div></div></section>
  <section className="ap-section ap-care"><div className="ap-inner" style={{display:'block'}}><div className="ap-care-head"><div className="ap-kicker">Care Discovery</div><h2>Find care with more context before you book.</h2><p>Doctor and hospital discovery belong together: understand your options first, then move into the appointment journey when you are ready.</p></div><div className="ap-care-grid"><article className="ap-care-card"><div className="ap-care-photo" style={{backgroundImage:"url('https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=1200&q=86')"}}/><div className="ap-care-body"><div className="ap-card-kicker" style={{color:'#2563EB'}}>FIND DOCTORS</div><h3>Choose a doctor with more confidence.</h3><p>Search by specialty and location, review profiles and consultation options, then move directly into booking.</p><Link href="/doctors" style={{color:'#2563EB'}}>Find Doctors →</Link></div></article><article className="ap-care-card"><div className="ap-care-photo" style={{backgroundImage:"url('https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=86')"}}/><div className="ap-care-body"><div className="ap-card-kicker" style={{color:'#EA580C'}}>FIND HOSPITALS</div><h3>Know more before you travel for care.</h3><p>Compare departments, facilities, hospital-specific OPD information and affiliated doctors before deciding where to visit.</p><Link href="/hospitals" style={{color:'#EA580C'}}>Find Hospitals →</Link></div></article></div></div></section>
  <section className="ap-section ap-doctor reverse"><div className="ap-inner"><div className="ap-visual"><div className="ap-doctor-photo"/></div><div className="ap-copy"><div className="ap-kicker">For doctors</div><h2>A connected workspace for your practice.</h2><p>HealthConnect brings the doctor&apos;s patient relationships, schedule and consultation workflow into one professional workspace without making appointments a separate product.</p><div className="ap-doctor-chips"><div className="ap-doctor-chip"><b>My Patients</b><span>Patient-shared health context and longitudinal information.</span></div><div className="ap-doctor-chip"><b>Practice & Schedule</b><span>Availability, appointments and follow-ups in one workflow.</span></div><div className="ap-doctor-chip"><b>Consultations</b><span>Move from booking through consultation and continued care.</span></div></div><button className="ap-cta" style={{background:'#0F766E'}} onClick={openDoctor}>Explore Doctor Platform →</button></div></div></section>
  </section>;
}
