'use client';

import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuthStore } from '@/store/authStore';
import { useUIStore } from '@/store/uiStore';

type PathKind='health'|'doctor'|'hospital'|'community'|'knowledge'|'practice';
type PathItem={title:string;desc:string;detail:string;href?:string;action:string;color:string;wash:string;kind:PathKind};

const PATHS:PathItem[]=[
  {title:'My Health',desc:'Your private place for reports, medicines, symptoms, vitals and appointments.',detail:'Health timeline · reminders · records',action:'Explore My Health',color:'#0B8F7C',wash:'#EEF9F6',kind:'health'},
  {title:'Find Doctors',desc:'Search by specialty and location, review profiles and consultation options.',detail:'Profiles · availability · booking',href:'/doctors',action:'Find Doctors',color:'#2563EB',wash:'#F1F6FF',kind:'doctor'},
  {title:'Find Hospitals',desc:'Compare departments, facilities, OPD information and affiliated doctors.',detail:'Departments · OPD · facilities',href:'/hospitals',action:'Find Hospitals',color:'#EA580C',wash:'#FFF5ED',kind:'hospital'},
  {title:'Health Communities',desc:'Condition-focused spaces for lived experience, practical questions and peer support.',detail:'Peer support · moderation · privacy',href:'/communities',action:'Explore Communities',color:'#7C3AED',wash:'#F7F1FF',kind:'community'},
  {title:'Knowledge Hub',desc:'India-focused health explainers that help you understand topics and prepare questions.',detail:'Explain · learn · prepare',href:'/learn',action:'Visit Knowledge Hub',color:'#0284C7',wash:'#EFF8FD',kind:'knowledge'},
  {title:'Doctor Platform',desc:'A connected workspace for patients, schedules, consultations and follow-up.',detail:'My Patients · schedule · consultations',action:'Explore Doctor Platform',color:'#0F766E',wash:'#EEF8F6',kind:'practice'},
];

function PathIcon({kind}:{kind:PathKind}){
  const common={width:26,height:26,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.8,strokeLinecap:'round' as const,strokeLinejoin:'round' as const};
  if(kind==='health')return <svg {...common}><path d="M12 21s-7-4.35-7-10a4 4 0 0 1 7-2.3A4 4 0 0 1 19 11c0 5.65-7 10-7 10Z"/><path d="M9 12h6M12 9v6"/></svg>;
  if(kind==='doctor')return <svg {...common}><circle cx="9" cy="7" r="3"/><path d="M3.5 20v-2a5.5 5.5 0 0 1 11 0v2M17 8v7a3 3 0 0 0 6 0v-2M21 10v3"/></svg>;
  if(kind==='hospital')return <svg {...common}><path d="M4 21V5h11v16M15 9h5v12M8 9h3M9.5 7.5v3M7 14h2M11 14h2M7 18h2M11 18h2"/></svg>;
  if(kind==='community')return <svg {...common}><circle cx="8" cy="9" r="3"/><circle cx="17" cy="8" r="2.5"/><path d="M2.5 20a5.5 5.5 0 0 1 11 0M14 14a4.5 4.5 0 0 1 7.5 3.4"/></svg>;
  if(kind==='knowledge')return <svg {...common}><path d="M4 5.5A3.5 3.5 0 0 1 7.5 2H12v18H7.5A3.5 3.5 0 0 0 4 23V5.5ZM20 5.5A3.5 3.5 0 0 0 16.5 2H12v18h4.5A3.5 3.5 0 0 1 20 23V5.5Z"/></svg>;
  return <svg {...common}><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 8h10M7 12h4M7 16h7"/></svg>;
}

export default function AudienceJourneys(){
  const router=useRouter();
  const {user,isAuthenticated}=useAuthStore();
  const {openAuthModal}=useUIStore();
  const openPatient=()=>{if(!isAuthenticated||!user){try{sessionStorage.setItem('hc_post_login_redirect','/dashboard')}catch{};openAuthModal('login');return;}const role=String(user.role||'').toUpperCase();router.push(role==='PATIENT'?'/dashboard':role==='DOCTOR'?'/doctor-dashboard':role==='HOSPITAL'?'/hospital-dashboard':'/admin-dashboard');};
  const openDoctor=()=>{if(isAuthenticated&&user){const role=String(user.role||'').toUpperCase();router.push(role==='DOCTOR'?'/doctor-dashboard':role==='PATIENT'?'/dashboard':role==='HOSPITAL'?'/hospital-dashboard':'/admin-dashboard');return;}try{sessionStorage.setItem('hc_signup_role','DOCTOR')}catch{};openAuthModal('register');};
  const act=(item:PathItem)=>{if(item.href){router.push(item.href);return;}if(item.kind==='health')openPatient();else openDoctor();};

  return <section className="ap-root" id="platform-tour"><style>{`
    .ap-root{font-family:'DM Sans',Arial,sans-serif;color:#10243C;background:#fff}.ap-inner{max-width:1340px;margin:0 auto}.ap-kicker{font-size:13px;font-weight:900;letter-spacing:.17em;text-transform:uppercase;color:#0B8F7C;margin-bottom:9px}
    .ap-overview{padding:62px 28px 68px;background:#fff}.ap-intro{text-align:center;max-width:820px;margin:0 auto 30px}.ap-intro h2,.ap-section h2{font-family:'Sora','DM Sans',sans-serif;color:#0B1F36;letter-spacing:-.045em;margin:0}.ap-intro h2{font-size:clamp(2rem,2.8vw,3rem);line-height:1.07}.ap-intro p{font-size:16px;line-height:1.6;color:#587086;margin:11px auto 0;max-width:740px}
    .ap-grid{display:grid;grid-template-columns:repeat(6,1fr);border:1px solid #DCE8E7;border-radius:20px;overflow:hidden;box-shadow:0 12px 30px rgba(20,65,72,.055)}.ap-card{min-height:250px;padding:22px 18px 20px;display:flex;flex-direction:column;border-right:1px solid #DCE8E7}.ap-card:last-child{border-right:0}.ap-icon{width:48px;height:48px;border-radius:14px;display:grid;place-items:center;margin-bottom:14px}.ap-card h3{font-family:'Sora','DM Sans',sans-serif;font-size:18px;line-height:1.24;margin:0 0 9px;color:#10243C}.ap-card>p{font-size:13.5px;line-height:1.55;color:#546E81;margin:0 0 12px}.ap-detail{font-size:12.5px;line-height:1.45;color:#6B7F8D;margin-bottom:17px}.ap-link{margin-top:auto;border:0;background:transparent;padding:0;align-self:flex-start;font:900 13px 'DM Sans',Arial,sans-serif;cursor:pointer}
    .ap-section{padding:72px 28px}.ap-section .ap-inner{display:grid;grid-template-columns:minmax(400px,.92fr) minmax(0,1.08fr);gap:60px;align-items:center}.ap-section h2{font-size:clamp(2.15rem,3vw,3.2rem);line-height:1.05;max-width:650px}.ap-copy>p{font-size:16px;line-height:1.65;color:#587086;max-width:650px;margin:14px 0 20px}.ap-benefits{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:20px}.ap-benefit{padding:15px 14px;border:1px solid #D7E7E4;border-radius:13px;background:rgba(255,255,255,.74)}.ap-benefit-icon{width:32px;height:32px;border-radius:10px;display:grid;place-items:center;background:#D8F2EC;color:#087F70;font-weight:900;margin-bottom:10px}.ap-benefit b{display:block;font-size:14px;color:#17364C;margin-bottom:4px}.ap-benefit span{display:block;font-size:13px;line-height:1.5;color:#617789}.ap-cta{display:inline-flex;margin-top:22px;border-radius:10px;padding:11px 17px;color:#fff;border:0;font:900 13.5px 'DM Sans',Arial,sans-serif;cursor:pointer}
    .ap-care{background:linear-gradient(135deg,#EFF8F7,#F7FAFC)}.ap-care-head{display:grid;grid-template-columns:minmax(280px,.68fr) minmax(0,1.32fr);gap:48px;align-items:end;margin-bottom:28px}.ap-care-head h2{font-size:clamp(2rem,2.8vw,3rem);max-width:610px}.ap-care-head p{font-size:15px;line-height:1.6;color:#60778A;margin:0;max-width:620px}.ap-care-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.ap-care-card{background:#fff;border:1px solid #DCE7EA;border-radius:19px;overflow:hidden;box-shadow:0 10px 28px rgba(20,54,70,.055)}.ap-care-photo{aspect-ratio:16/8.4;background-size:cover;background-position:center}.ap-care-body{padding:20px 22px 22px}.ap-card-kicker{font-size:13px;font-weight:900;letter-spacing:.14em;text-transform:uppercase}.ap-care-body h3{font-family:'Sora',sans-serif;font-size:21px;letter-spacing:-.035em;margin:7px 0 8px}.ap-care-body p{font-size:14px;line-height:1.55;color:#60768A;margin:0 0 13px}.ap-care-body a{font-size:13.5px;font-weight:900;text-decoration:none}
    .ap-health{background:#fff}.ap-health-ui{width:min(100%,530px);background:#fff;border:1px solid #CDE0DC;border-radius:20px;padding:21px;box-shadow:0 20px 45px rgba(20,73,68,.10);position:relative}.ap-ui-head{display:flex;justify-content:space-between;align-items:center;padding-bottom:13px;border-bottom:1px solid #E6EFED;color:#567381;font-size:13px}.ap-ui-head b{color:#17364C;font-size:14px}.ap-ui-kpis{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:15px 0}.ap-ui-kpi{background:#F1F7F5;border-radius:10px;padding:12px;color:#6C818D;font-size:11.5px}.ap-ui-kpi strong{display:block;color:#0B8F7C;font-size:22px;margin-top:4px}.ap-ui-row{min-height:38px;background:#F2F6F7;border-radius:9px;margin:7px 0;padding:0 12px;display:flex;align-items:center;justify-content:space-between;color:#5B7181;font-size:12.5px}.ap-phone{position:absolute;right:-20px;bottom:-22px;width:145px;height:245px;border:7px solid #12374A;background:#fff;border-radius:27px;padding:21px 10px 10px;box-shadow:0 15px 32px rgba(15,44,58,.15)}.ap-phone:before{content:'';position:absolute;top:8px;left:50%;transform:translateX(-50%);width:52px;height:5px;border-radius:5px;background:#12374A}.ap-phone b{display:block;font-size:12px;margin-bottom:9px}.ap-phone span{display:block;background:#F2F6F7;border-radius:7px;padding:7px;margin:7px 0;color:#607686;font-size:10.5px}
    @media(max-width:1120px){.ap-grid{grid-template-columns:repeat(3,1fr)}.ap-card:nth-child(3){border-right:0}.ap-card:nth-child(n+4){border-top:1px solid #DCE8E7}.ap-section .ap-inner{grid-template-columns:1fr;gap:36px}.ap-care-head{grid-template-columns:1fr;gap:8px}.ap-benefits{grid-template-columns:repeat(3,1fr)}}
    @media(max-width:720px){.ap-overview,.ap-section{padding:50px 14px}.ap-intro{text-align:left}.ap-grid{grid-template-columns:1fr 1fr}.ap-card{border-right:1px solid #DCE8E7;border-top:1px solid #DCE8E7}.ap-card:nth-child(-n+2){border-top:0}.ap-card:nth-child(even){border-right:0}.ap-card:nth-child(3){border-right:1px solid #DCE8E7}.ap-care-grid{grid-template-columns:1fr}.ap-benefits{grid-template-columns:1fr}.ap-health-ui{margin-right:14px}.ap-phone{right:-8px}.ap-care-photo{aspect-ratio:16/9}}
    @media(max-width:480px){.ap-grid{grid-template-columns:1fr}.ap-card,.ap-card:nth-child(3){border-right:0}.ap-card:nth-child(2){border-top:1px solid #DCE8E7}.ap-phone{position:relative;right:auto;bottom:auto;margin:16px auto 0;width:160px;height:235px}.ap-health-ui{margin-right:0}.ap-ui-kpis{grid-template-columns:1fr 1fr}.ap-ui-kpi:last-child{grid-column:1/-1}}
  `}</style>

  <div className="ap-overview"><div className="ap-inner"><div className="ap-intro"><div className="ap-kicker">Your complete healthcare journey</div><h2>Everything you need to understand HealthConnect at a glance.</h2><p>Each area solves a different part of the healthcare journey. Together they connect discovery, personal health information, peer support, learning and professional care workflows.</p></div><div className="ap-grid">{PATHS.map(item=><article className="ap-card" key={item.title} style={{background:item.wash}}><span className="ap-icon" style={{background:`${item.color}12`,color:item.color}}><PathIcon kind={item.kind}/></span><h3>{item.title}</h3><p>{item.desc}</p><div className="ap-detail">{item.detail}</div><button className="ap-link" style={{color:item.color}} onClick={()=>act(item)}>{item.action} →</button></article>)}</div></div></div>

  <section className="ap-section ap-care"><div className="ap-inner" style={{display:'block'}}><div className="ap-care-head"><div><div className="ap-kicker">Care Discovery</div><h2>Find care with more context before you book.</h2></div><p>Doctor and hospital discovery belong together: understand your options first, then move into the appointment journey when you are ready.</p></div><div className="ap-care-grid"><article className="ap-care-card"><div className="ap-care-photo" style={{backgroundImage:"url('https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=1200&q=85')",backgroundPosition:'center 32%'}}/><div className="ap-care-body"><div className="ap-card-kicker" style={{color:'#2563EB'}}>Find Doctors</div><h3>Choose a doctor with more confidence.</h3><p>Search by specialty and location, review profiles and consultation options, then move directly into booking.</p><Link href="/doctors" style={{color:'#2563EB'}}>Find Doctors →</Link></div></article><article className="ap-care-card"><div className="ap-care-photo" style={{backgroundImage:"url('https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&q=85')",backgroundPosition:'center'}}/><div className="ap-care-body"><div className="ap-card-kicker" style={{color:'#EA580C'}}>Find Hospitals</div><h3>Know more before you travel for care.</h3><p>Compare departments, facilities, hospital-specific OPD information and affiliated doctors before deciding where to visit.</p><Link href="/hospitals" style={{color:'#EA580C'}}>Find Hospitals →</Link></div></article></div></div></section>

  <section className="ap-section ap-health"><div className="ap-inner"><div className="ap-visual"><div className="ap-health-ui"><div className="ap-ui-head"><b>My Health</b><span>Your private health workspace</span></div><div className="ap-ui-kpis"><div className="ap-ui-kpi">HEALTH SCORE<strong>82</strong></div><div className="ap-ui-kpi">UPCOMING<strong>2</strong></div><div className="ap-ui-kpi">REPORTS<strong>8</strong></div></div><div className="ap-ui-row"><span>Reports & prescriptions</span><b>8</b></div><div className="ap-ui-row"><span>Medicines & reminders</span><b>5</b></div><div className="ap-ui-row"><span>Symptoms & vitals</span><b>Timeline</b></div><div className="ap-phone"><b>Health timeline</b><span>Prescription added</span><span>Lab report</span><span>Follow-up visit</span><span>Medicine reminder</span></div></div></div><div className="ap-copy"><div className="ap-kicker">For patients & families</div><h2>Your health journey, organised and always with you.</h2><p>My Health keeps reports, prescriptions, medicines, symptoms, vitals and appointments organised in one authenticated patient workspace.</p><div className="ap-benefits"><div className="ap-benefit"><span className="ap-benefit-icon">▣</span><b>Keep it together</b><span>Carry important health information as one journey instead of scattered records.</span></div><div className="ap-benefit"><span className="ap-benefit-icon">♢</span><b>Stay ahead</b><span>Track medicines, reminders, upcoming care and follow-ups in one place.</span></div><div className="ap-benefit"><span className="ap-benefit-icon">◎</span><b>Be better prepared</b><span>Bring useful health context into your next conversation with a doctor.</span></div></div><button className="ap-cta" style={{background:'#0B8F7C'}} onClick={openPatient}>Explore My Health →</button></div></div></section>
  </section>;
}
