'use client';

import Link from 'next/link';

export default function CareDiscoveryStrip(){
  return <section className="care-discovery" id="care-discovery">
    <style>{`
      .care-discovery{font-family:'DM Sans',Arial,sans-serif;background:linear-gradient(180deg,#F4F9FB 0%,#F8FBFC 100%);padding:64px 28px 72px;color:#10243C}.care-inner{max-width:1380px;margin:0 auto}.care-head{text-align:center;max-width:920px;margin:0 auto 32px}.care-kicker{font-size:14px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:#0B8F7C;margin-bottom:9px}.care-head h2{font-family:'Sora','DM Sans',sans-serif;font-size:clamp(2.25rem,3.2vw,3.45rem);line-height:1.04;letter-spacing:-.048em;color:#0D263A;margin:0}.care-head p{font-size:16px;line-height:1.62;color:#526A7C;margin:14px auto 0;max-width:790px}.care-grid{display:grid;grid-template-columns:1fr 1fr;gap:22px}.care-card{background:#fff;border:1px solid #D9E5E9;border-radius:22px;overflow:hidden;box-shadow:0 14px 34px rgba(20,57,72,.07);text-decoration:none;color:#10243C;transition:transform .18s ease,box-shadow .18s ease}.care-card:hover{transform:translateY(-2px);box-shadow:0 18px 40px rgba(20,57,72,.10)}.care-image{aspect-ratio:16/7.7;background-size:cover;background-position:center}.care-card.doctor .care-image{background-image:url('https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=1400&q=88');background-position:center 30%}.care-card.hospital .care-image{background-image:url('https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=1400&q=88');background-position:center 48%}.care-body{padding:22px 24px 24px}.care-tag{font-size:13px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;margin-bottom:7px}.care-card.doctor .care-tag,.care-card.doctor .care-action{color:#2563EB}.care-card.hospital .care-tag,.care-card.hospital .care-action{color:#EA580C}.care-body h3{font-family:'Sora','DM Sans',sans-serif;font-size:23px;line-height:1.2;letter-spacing:-.035em;margin:0 0 9px}.care-body p{font-size:14.5px;line-height:1.58;color:#526A7C;margin:0 0 15px;max-width:650px}.care-action{font-size:13.5px;font-weight:900}
      @media(max-width:820px){.care-grid{grid-template-columns:1fr}.care-head{text-align:left}.care-image{aspect-ratio:16/8.5}}
      @media(max-width:560px){.care-discovery{padding:52px 14px 58px}.care-head{margin-bottom:24px}.care-body{padding:19px 18px 21px}.care-body h3{font-size:21px}.care-image{aspect-ratio:16/9}}
    `}</style>
    <div className="care-inner"><div className="care-head"><div className="care-kicker">Care Discovery</div><h2>Find care with more context before you book.</h2><p>Understand your options first, then move into the appointment journey when you are ready. HealthConnect keeps doctor and hospital discovery connected to the wider care experience.</p></div><div className="care-grid"><Link href="/doctors" className="care-card doctor"><div className="care-image"/><div className="care-body"><div className="care-tag">Find Doctors</div><h3>Choose a doctor with more confidence.</h3><p>Search by specialty and location, review profiles and consultation options, and move directly into booking.</p><span className="care-action">Find Doctors →</span></div></Link><Link href="/hospitals" className="care-card hospital"><div className="care-image"/><div className="care-body"><div className="care-tag">Find Hospitals</div><h3>Know more before you travel for care.</h3><p>Compare departments, facilities, hospital OPD information and affiliated doctors before deciding where to visit.</p><span className="care-action">Find Hospitals →</span></div></Link></div></div>
  </section>;
}
