'use client';

import Link from 'next/link';

export default function CareDiscoveryStrip(){
  return <section className="care-discovery" id="care-discovery" aria-labelledby="care-discovery-title">
    <style>{`
      .care-discovery{font-family:'DM Sans',Arial,sans-serif;background:#B9C8D2;padding:48px 22px 54px;color:#10243C;border-top:1px solid #A5B8C4;border-bottom:1px solid #A5B8C4;scroll-margin-top:90px}.care-inner{max-width:1340px;margin:0 auto}.care-head{display:grid;grid-template-columns:minmax(0,1fr) minmax(340px,.58fr);gap:44px;align-items:end;margin:0 6px 22px}.care-kicker{font-size:12.5px;font-weight:900;letter-spacing:.17em;text-transform:uppercase;color:#315B69;margin-bottom:7px}.care-head h2{font-family:'Sora','DM Sans',sans-serif;font-size:clamp(2.1rem,2.75vw,2.95rem);line-height:1.03;letter-spacing:-.048em;color:#0D263A;margin:0}.care-head p{font-size:15.5px;line-height:1.52;color:#405D70;margin:0 0 4px;max-width:560px}.care-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.care-card{border:1px solid #879DAA;border-radius:22px;overflow:hidden;box-shadow:0 16px 34px rgba(24,50,67,.14);color:#fff;transition:transform .18s ease,box-shadow .18s ease;background:#29485D}.care-card:hover{transform:translateY(-2px);box-shadow:0 20px 40px rgba(24,50,67,.18)}.care-image{aspect-ratio:16/7.2;background-size:cover;background-position:center;background-color:#DDE7EA;position:relative}.care-image:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 55%,rgba(14,35,48,.24))}.care-card.doctor .care-image{background-image:url('https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=1400&q=88');background-position:center 30%}.care-card.hospital .care-image{background-image:url('https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=1400&q=88');background-position:center 48%}.care-card.doctor{background:#2D4F63}.care-card.hospital{background:#405B58}.care-body{padding:20px 21px 22px}.care-tag{font-size:12px;font-weight:900;letter-spacing:.13em;text-transform:uppercase;margin-bottom:6px}.care-card.doctor .care-tag{color:#A9D2F2}.care-card.hospital .care-tag{color:#B9DDD1}.care-body h3{font-family:'Sora','DM Sans',sans-serif;font-size:22px;line-height:1.22;letter-spacing:-.035em;margin:0 0 7px;color:#fff}.care-body p{font-size:14px;line-height:1.5;color:#DDE8ED;margin:0 0 14px;max-width:650px}.care-action{display:inline-flex;align-items:center;justify-content:center;text-decoration:none;border-radius:9px;padding:9px 12px;font-size:11.5px;font-weight:900;transition:transform .16s ease,background .16s ease}.care-action:hover{transform:translateY(-1px)}.care-card.doctor .care-action{background:#E7F0F7;color:#254B60;border:1px solid #C6D9E6}.care-card.hospital .care-action{background:#E7F1ED;color:#355651;border:1px solid #C5DCD3}.care-action:focus-visible{outline:3px solid rgba(255,255,255,.45);outline-offset:3px}.care-caption{display:block;margin-top:9px;font-size:10.3px;color:#BFD0D9}
      @media(max-width:820px){.care-head{grid-template-columns:1fr;gap:10px}.care-grid{grid-template-columns:1fr}.care-image{aspect-ratio:16/8.2}}
      @media(max-width:560px){.care-discovery{padding:40px 12px 44px}.care-head{margin:0 4px 18px}.care-head h2{font-size:2.1rem}.care-head p{font-size:14.5px}.care-body{padding:18px}.care-body h3{font-size:20px}.care-image{aspect-ratio:16/9}}
    `}</style>
    <div className="care-inner">
      <div className="care-head"><div><div className="care-kicker">Care Discovery</div><h2 id="care-discovery-title">Find care with more context before you book.</h2></div><p>Understand your options first, then open the full directory when you are ready to compare and book.</p></div>
      <div className="care-grid">
        <article className="care-card doctor" id="care-doctors"><div className="care-image" role="img" aria-label="Doctor consultation"/><div className="care-body"><div className="care-tag">Find Doctors</div><h3>Choose a doctor with more confidence.</h3><p>Search by specialty and location, review profiles and consultation options, then continue into the full doctor directory.</p><Link href="/doctors" className="care-action">Open Doctor Directory</Link><span className="care-caption">Profiles · specialties · availability · booking</span></div></article>
        <article className="care-card hospital" id="care-hospitals"><div className="care-image" role="img" aria-label="Hospital care facility"/><div className="care-body"><div className="care-tag">Find Hospitals</div><h3>Know more before you travel for care.</h3><p>Compare departments, facilities, hospital OPD information and affiliated doctors before deciding where to visit.</p><Link href="/hospitals" className="care-action">Open Hospital Directory</Link><span className="care-caption">Departments · facilities · doctors · OPD</span></div></article>
      </div>
    </div>
  </section>;
}
