'use client';

import { useMemo, useState } from 'react';
import Link from 'next/link';
import type { CSSProperties } from 'react';

const ARTICLES=[
  {cat:'Diabetes',title:'HbA1c — What Your Diabetes Numbers Really Mean for Indians',summary:'Understand what the number represents and prepare better questions for your next consultation.',href:'/learn/hba1c-what-your-diabetes-numbers-really-mean',photo:'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=1200&q=86',color:'#2459C4',tint:'#DCE7F5',border:'#B9CDE8'},
  {cat:'Cardiology',title:'Why Heart Attacks in Young Indians Are Rising',summary:'Learn common risk factors, warning signs and what to discuss with a healthcare professional.',href:'/learn/heart-attacks-young-indians',photo:'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=1200&q=86',color:'#B4234D',tint:'#F1DDE3',border:'#DFBAC6'},
  {cat:'Women Health',title:'PCOD & PCOS: A Guide for Indian Women',summary:'Understand common patterns and the care conversations that can make the condition easier to navigate.',href:'/learn/pcos-complete-guide-indian-women',photo:'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=1200&q=86',color:'#6D45C6',tint:'#E7DFF3',border:'#CFC1E8'},
  {cat:'Mental Health',title:'Managing Anxiety and Depression: Breaking the Stigma in India',summary:'Recognise common signs, know when to seek help and prepare for a more informed conversation.',href:'/learn/mental-health-india-breaking-stigma',photo:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&q=86',color:'#087D5A',tint:'#D8EAE1',border:'#B9D7C9'},
] as const;

export default function KnowledgeResources(){
  const [start,setStart]=useState(0);
  const visible=useMemo(()=>[0,1,2].map(offset=>ARTICLES[(start+offset)%ARTICLES.length]),[start]);
  const previous=()=>setStart(current=>(current-1+ARTICLES.length)%ARTICLES.length);
  const next=()=>setStart(current=>(current+1)%ARTICLES.length);

  return <section className="knowledge-section" id="knowledge-hub" aria-labelledby="knowledge-title"><style>{`
    .knowledge-section{background:#E5EBF1;padding:50px 22px 54px;font-family:'DM Sans',Arial,sans-serif;border-top:1px solid #D4DEE7;color:#10243C}.knowledge-inner{max-width:1340px;margin:0 auto}.knowledge-head{display:grid;grid-template-columns:minmax(0,1.08fr) minmax(320px,.72fr);gap:46px;align-items:end;margin:0 6px 22px}.knowledge-kicker{font-size:12.5px;font-weight:900;letter-spacing:.17em;color:#2459C4;margin-bottom:7px}.knowledge-title{font-family:'Sora','DM Sans',sans-serif;font-size:clamp(2.05rem,2.7vw,2.9rem);line-height:1.04;letter-spacing:-.045em;color:#0F172A;margin:0;max-width:720px}.knowledge-head-right{max-width:500px}.knowledge-head-right p{font-size:15.5px;line-height:1.52;color:#465F75;margin:0 0 13px}.knowledge-head-actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap}.knowledge-all{display:inline-flex;border:1px solid #AFC6E5;background:#D7E4F3;border-radius:10px;padding:10px 14px;color:#1E4FAF;text-decoration:none;font-size:12.5px;font-weight:900}.knowledge-all:focus-visible,.knowledge-arrow:focus-visible,.knowledge-card:focus-visible{outline:3px solid rgba(37,99,235,.22);outline-offset:3px}.knowledge-arrow{width:38px;height:38px;border-radius:50%;border:1px solid #BAC9D7;background:#D5E0E9;color:#17384A;font-size:19px;cursor:pointer}.knowledge-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.knowledge-card{text-decoration:none;color:inherit;border:1px solid var(--card-border);border-radius:20px;overflow:hidden;background:var(--card-tint);transition:.18s;box-shadow:0 10px 25px rgba(15,23,42,.06);position:relative}.knowledge-card:before{content:'';position:absolute;left:0;right:0;top:0;height:4px;background:var(--card-accent);z-index:3}.knowledge-card:hover{transform:translateY(-3px);box-shadow:0 16px 32px rgba(15,23,42,.11)}.knowledge-photo{aspect-ratio:16/8.4;background-size:cover;background-position:center;position:relative;background-color:#D8E1E7}.knowledge-photo:after{content:'';position:absolute;inset:0;background:linear-gradient(to top,rgba(15,23,42,.17),transparent 58%)}.knowledge-body{padding:17px 18px 19px;min-height:188px;display:flex;flex-direction:column}.knowledge-cat{display:inline-flex;align-self:flex-start;font-size:11.5px;font-weight:900;letter-spacing:.07em;text-transform:uppercase;padding:5px 8px;border-radius:999px;margin-bottom:9px;background:rgba(255,255,255,.48)}.knowledge-card h3{font-family:'Sora',sans-serif;font-size:17px;line-height:1.34;color:#0F172A;margin:0 0 8px}.knowledge-summary{font-size:13.5px;line-height:1.48;color:#415D70;margin:0 0 14px}.knowledge-read{font-size:12.5px;font-weight:900;color:var(--card-accent);margin-top:auto}.knowledge-disclaimer{margin-top:16px;padding:12px 14px;background:#D3DEE6;border:1px solid #C2D0DA;border-radius:12px;color:#3F566B;font-size:12.5px;line-height:1.45}.knowledge-disclaimer strong{color:#263D52}
    @media(max-width:980px){.knowledge-head{grid-template-columns:1fr;gap:11px}.knowledge-grid{grid-template-columns:1fr 1fr}.knowledge-card:last-child{display:none}}
    @media(max-width:650px){.knowledge-section{padding:42px 12px 46px}.knowledge-head{margin:0 4px 18px}.knowledge-title{font-size:2.15rem}.knowledge-grid{grid-template-columns:1fr}.knowledge-card:nth-child(n+2){display:none}.knowledge-head-right p{font-size:14.5px}.knowledge-card h3{font-size:17px}.knowledge-body{min-height:0}}
  `}</style><div className="knowledge-inner"><div className="knowledge-head"><div><div className="knowledge-kicker">KNOWLEDGE HUB</div><h2 className="knowledge-title" id="knowledge-title">Health information for better everyday decisions.</h2></div><div className="knowledge-head-right"><p>India-focused explainers help people understand common health topics and prepare better questions for a healthcare professional.</p><div className="knowledge-head-actions"><Link href="/learn" className="knowledge-all">Visit Knowledge Hub →</Link><button className="knowledge-arrow" type="button" aria-label="Previous knowledge articles" onClick={previous}>‹</button><button className="knowledge-arrow" type="button" aria-label="Next knowledge articles" onClick={next}>›</button></div></div></div><div className="knowledge-grid" aria-live="polite">{visible.map(article=><Link href={article.href} className="knowledge-card" key={`${start}-${article.href}`} style={{'--card-tint':article.tint,'--card-border':article.border,'--card-accent':article.color} as CSSProperties}><div className="knowledge-photo" style={{backgroundImage:`url(${article.photo})`}} role="img" aria-label={`${article.cat} health article`}/><div className="knowledge-body"><span className="knowledge-cat" style={{color:article.color}}>{article.cat}</span><h3>{article.title}</h3><p className="knowledge-summary">{article.summary}</p><span className="knowledge-read">Read article →</span></div></Link>)}</div><div className="knowledge-disclaimer"><strong>Educational content supports informed conversations; it is not a diagnosis or personal treatment advice.</strong></div></div></section>;
}
