'use client';

import Link from 'next/link';

const ARTICLES = [
  {cat:'Diabetes',title:'HbA1c — What Your Diabetes Numbers Really Mean for Indians',href:'/learn/hba1c-what-your-diabetes-numbers-really-mean',photo:'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=700&q=80',color:'#2563EB'},
  {cat:'Cardiology',title:'Why Heart Attacks in Young Indians Are Rising: What You Need to Know',href:'/learn/heart-attacks-young-indians',photo:'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=700&q=80',color:'#E11D48'},
  {cat:'Women Health',title:'PCOD & PCOS: The Complete Guide for Indian Women',href:'/learn/pcos-complete-guide-indian-women',photo:'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=700&q=80',color:'#7C3AED'},
  {cat:'Mental Health',title:'Managing Anxiety and Depression: Breaking the Stigma in India',href:'/learn/mental-health-india-breaking-stigma',photo:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=700&q=80',color:'#059669'},
] as const;

export default function KnowledgeResources(){
  return <section className="knowledge-section"><style>{`
    .knowledge-section{background:#fff;padding:48px 28px 50px;font-family:'DM Sans',Arial,sans-serif}.knowledge-inner{max-width:1280px;margin:0 auto}.knowledge-head{display:flex;justify-content:space-between;align-items:end;gap:30px;margin-bottom:21px}.knowledge-kicker{font-size:10px;font-weight:900;letter-spacing:.18em;color:#2563EB;margin-bottom:8px}.knowledge-title{font-family:'Sora','DM Sans',sans-serif;font-size:clamp(2rem,3vw,3.35rem);line-height:1.04;letter-spacing:-.045em;color:#0F172A;margin:0}.knowledge-head-right{max-width:410px}.knowledge-head-right p{font-size:12px;line-height:1.6;color:#64748B;margin:0 0 11px}.knowledge-all{display:inline-flex;border:1px solid #2563EB;border-radius:8px;padding:8px 12px;color:#1D4ED8;text-decoration:none;font-size:9.5px;font-weight:900}.knowledge-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.knowledge-card{text-decoration:none;color:inherit;border:1px solid #E1E8EF;border-radius:15px;overflow:hidden;background:#fff;transition:.18s;box-shadow:0 5px 18px rgba(15,23,42,.035)}.knowledge-card:hover{transform:translateY(-2px);box-shadow:0 12px 28px rgba(15,23,42,.07)}.knowledge-photo{height:118px;background-size:cover;background-position:center;position:relative}.knowledge-photo:after{content:'';position:absolute;inset:0;background:linear-gradient(to top,rgba(15,23,42,.16),transparent 56%)}.knowledge-body{padding:13px}.knowledge-cat{display:inline-flex;font-size:8px;font-weight:900;letter-spacing:.08em;text-transform:uppercase;padding:4px 7px;border-radius:999px;margin-bottom:7px}.knowledge-card h3{font-family:'Sora',sans-serif;font-size:11.5px;line-height:1.4;color:#0F172A;margin:0 0 10px;min-height:49px}.knowledge-read{font-size:9px;font-weight:850;color:#2563EB}.knowledge-disclaimer{display:flex;justify-content:space-between;gap:18px;align-items:center;margin-top:16px;padding:10px 13px;background:#F8FAFC;border:1px solid #E5EAF0;border-radius:10px;color:#64748B;font-size:9px;line-height:1.45}.knowledge-disclaimer strong{color:#334155}
    @media(max-width:980px){.knowledge-grid{grid-template-columns:1fr 1fr}}@media(max-width:650px){.knowledge-section{padding:42px 14px}.knowledge-head{align-items:start;flex-direction:column}.knowledge-grid{grid-template-columns:1fr}.knowledge-card h3{min-height:0}.knowledge-disclaimer{align-items:start;flex-direction:column}}
  `}</style><div className="knowledge-inner"><div className="knowledge-head"><div><div className="knowledge-kicker">KNOWLEDGE HUB</div><h2 className="knowledge-title">Health information that helps you ask better questions.</h2></div><div className="knowledge-head-right"><p>India-focused health explainers and condition guides can help people prepare for more useful conversations with a healthcare professional.</p><Link href="/learn" className="knowledge-all">Visit Knowledge Hub →</Link></div></div><div className="knowledge-grid">{ARTICLES.map(article=><Link href={article.href} className="knowledge-card" key={article.href}><div className="knowledge-photo" style={{backgroundImage:`url(${article.photo})`}}/><div className="knowledge-body"><span className="knowledge-cat" style={{color:article.color,background:`${article.color}12`}}>{article.cat}</span><h3>{article.title}</h3><span className="knowledge-read">Read article →</span></div></Link>)}</div><div className="knowledge-disclaimer"><span><strong>Use knowledge as a starting point.</strong> Personal symptoms and treatment decisions belong in a conversation with a qualified healthcare professional.</span><span>Educational content is not a diagnosis.</span></div></div></section>;
}
