'use client';
import { useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';

const C={card:'#FFFFFF',border:'rgba(45,139,122,0.14)',teal:'#2D8B7A',text:'#1C3A35',muted:'#5A7184',green:'#16A34A',amber:'#D97706',red:'#DC2626',blue:'#2563EB'};
type Tab='doctors'|'hospitals';

export default function VerificationPage(){
  const [tab,setTab]=useState<Tab>('doctors');const [doctors,setDoctors]=useState<any[]>([]);const [hospitals,setHospitals]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<any>(null);const [reason,setReason]=useState('');const [acting,setActing]=useState(false);const [error,setError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [d,h]=await Promise.all([api.get('/admin/doctors/pending'),api.get('/admin/hospitals/pending')]);const dd=d?.data?.data??{};const hd=h?.data?.data??{};setDoctors(Array.isArray(dd)?dd:dd.doctors??[]);setHospitals(Array.isArray(hd)?hd:hd.hospitals??[]);}catch(e:any){setError(e?.response?.data?.message??'Unable to load verification queue.')}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  const doctorAct=async(d:any,action:'approve'|'reject')=>{if(action==='reject'&&!reason.trim()){alert('Please provide a rejection reason');return;}setActing(true);try{await api.post(`/admin/doctors/${d.id}/verify`,{action,reason:action==='reject'?reason:undefined});setSelected(null);setReason('');await load()}catch(e:any){setError(e?.response?.data?.message??'Doctor verification action failed.')}finally{setActing(false)}};
  const hospitalAct=async(h:any,action:'review'|'approve'|'reject')=>{if(action==='reject'&&!reason.trim()){alert('Please provide a rejection reason');return;}setActing(true);try{await api.post(`/admin/hospitals/${h.id}/verify`,{action,reason:reason.trim()||undefined});setSelected(null);setReason('');await load()}catch(e:any){setError(e?.response?.data?.message??'Hospital verification action failed.')}finally{setActing(false)}};
  if(loading)return <div style={{display:'flex',alignItems:'center',justifyContent:'center',minHeight:300}}>Loading verification queue…</div>;
  return <div style={{color:C.text,fontFamily:"'Inter',sans-serif"}}><div style={{marginBottom:20}}><h1 style={{margin:0,fontSize:24,fontWeight:700}}>Verification Center</h1><p style={{margin:'4px 0 0',color:C.muted,fontSize:13}}>Review healthcare professional and institutional verification submissions.</p></div>
    {error&&<div style={{padding:11,borderRadius:9,background:'#FEF2F2',color:C.red,marginBottom:12,fontSize:12}}>⚠ {error}</div>}
    <div style={{display:'flex',gap:8,marginBottom:16}}><button onClick={()=>setTab('doctors')} style={tabBtn(tab==='doctors')}>Doctors · {doctors.length}</button><button onClick={()=>setTab('hospitals')} style={tabBtn(tab==='hospitals')}>Hospitals · {hospitals.length}</button></div>
    {tab==='doctors'?<DoctorQueue rows={doctors} onApprove={d=>doctorAct(d,'approve')} onReject={d=>{setSelected({...d,_kind:'doctor'});setReason('')}}/>:<HospitalQueue rows={hospitals} onReview={h=>hospitalAct(h,'review')} onApprove={h=>hospitalAct(h,'approve')} onReject={h=>{setSelected({...h,_kind:'hospital'});setReason('')}}/>}
    {selected&&<div style={overlay}><div style={{background:'#fff',borderRadius:14,padding:24,width:'min(440px,94vw)',boxShadow:'0 20px 60px rgba(0,0,0,.16)'}}><h3 style={{margin:'0 0 7px'}}>Reject {selected._kind==='hospital'?selected.name:`Dr. ${selected.firstName} ${selected.lastName}`}?</h3><p style={{color:C.muted,fontSize:12}}>The account will be notified with this reason and can correct the information before resubmitting.</p><textarea value={reason} onChange={e=>setReason(e.target.value)} rows={4} placeholder="Reason for rejection (required)" style={{width:'100%',boxSizing:'border-box',border:`1px solid ${C.border}`,borderRadius:8,padding:10}}/><div style={{display:'flex',gap:8,marginTop:12}}><button onClick={()=>setSelected(null)} style={{...baseBtn,background:'#fff',color:C.muted,border:`1px solid ${C.border}`}}>Cancel</button><button disabled={acting} onClick={()=>selected._kind==='hospital'?hospitalAct(selected,'reject'):doctorAct(selected,'reject')} style={{...baseBtn,background:C.red,color:'#fff',flex:1}}>{acting?'Processing…':'Confirm rejection'}</button></div></div></div>}
  </div>;
}

function DoctorQueue({rows,onApprove,onReject}:{rows:any[];onApprove:(d:any)=>void;onReject:(d:any)=>void}){if(!rows.length)return <Empty label="No doctors pending verification."/>;return <div style={{display:'grid',gap:11}}>{rows.map(d=><div key={d.id} style={card}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'start'}}><div><div style={{fontWeight:750}}>Dr. {d.firstName} {d.lastName}</div><div style={sub}>{d.user?.email} · {d.specialization||'Specialization not added'}</div><div style={{display:'flex',gap:18,flexWrap:'wrap',marginTop:10}}>{[['License',d.medicalLicenseNumber],['Council',d.medicalCouncil],['State',d.licenseState],['Experience',d.experienceYears!=null?`${d.experienceYears} yrs`:null]].map(([k,v])=><Meta key={String(k)} label={String(k)} value={v}/>)}</div></div><div style={{display:'flex',gap:7}}><button onClick={()=>onReject(d)} style={{...baseBtn,background:'#FEE2E2',color:C.red}}>Reject</button><button onClick={()=>onApprove(d)} style={{...baseBtn,background:C.green,color:'#fff'}}>✓ Approve</button></div></div></div>)}</div>}

function HospitalQueue({rows,onReview,onApprove,onReject}:{rows:any[];onReview:(h:any)=>void;onApprove:(h:any)=>void;onReject:(h:any)=>void}){if(!rows.length)return <Empty label="No hospitals pending verification."/>;return <div style={{display:'grid',gap:11}}>{rows.map(h=><div key={h.id} style={card}><div style={{display:'flex',justifyContent:'space-between',gap:16,alignItems:'start'}}><div style={{flex:1}}><div style={{display:'flex',alignItems:'center',gap:7,flexWrap:'wrap'}}><div style={{fontWeight:780}}>{h.name}</div><span style={{fontSize:9.5,fontWeight:800,padding:'3px 7px',borderRadius:999,background:h.verificationStatus==='UNDER_REVIEW'?'#EDE9FE':'#DBEAFE',color:h.verificationStatus==='UNDER_REVIEW'?'#7C3AED':C.blue}}>{String(h.verificationStatus).replaceAll('_',' ')}</span></div><div style={sub}>{h.user?.email} · {[h.city,h.state].filter(Boolean).join(', ')}</div><div style={{display:'flex',gap:18,flexWrap:'wrap',marginTop:10}}><Meta label="Registration" value={h.registrationNumber}/><Meta label="Authority" value={h.registrationAuthority}/><Meta label="Type" value={h.hospitalType}/><Meta label="Beds" value={h.totalBeds}/><Meta label="Documents" value={Array.isArray(h.verificationDocuments)?h.verificationDocuments.length:0}/></div>{Array.isArray(h.verificationDocuments)&&h.verificationDocuments.length>0&&<div style={{marginTop:10,fontSize:11}}>{h.verificationDocuments.map((url:string,i:number)=><a key={url} href={url} target="_blank" rel="noreferrer" style={{color:C.blue,marginRight:10}}>Document {i+1} ↗</a>)}</div>}</div><div style={{display:'flex',gap:7,flexWrap:'wrap',justifyContent:'flex-end'}}>{h.verificationStatus==='SUBMITTED'&&<button onClick={()=>onReview(h)} style={{...baseBtn,background:'#EDE9FE',color:'#7C3AED'}}>Start review</button>}<button onClick={()=>onReject(h)} style={{...baseBtn,background:'#FEE2E2',color:C.red}}>Reject</button><button onClick={()=>onApprove(h)} style={{...baseBtn,background:C.green,color:'#fff'}}>✓ Verify</button></div></div></div>)}</div>}
function Meta({label,value}:{label:string;value:any}){return <div><div style={{fontSize:9.5,color:C.muted,textTransform:'uppercase'}}>{label}</div><div style={{fontSize:11.5,fontWeight:600,marginTop:2}}>{value??'—'}</div></div>}
function Empty({label}:{label:string}){return <div style={{background:C.card,border:`1px solid ${C.border}`,borderRadius:12,padding:50,textAlign:'center'}}><div style={{fontSize:35}}>✅</div><h3 style={{margin:'8px 0 3px'}}>All caught up</h3><div style={{fontSize:12,color:C.muted}}>{label}</div></div>}
const card:React.CSSProperties={background:C.card,border:`1px solid ${C.border}`,borderRadius:12,padding:18,boxShadow:'0 1px 4px rgba(0,0,0,.035)'};const sub:React.CSSProperties={fontSize:11,color:C.muted,marginTop:4};const baseBtn:React.CSSProperties={border:'none',borderRadius:8,padding:'8px 12px',fontWeight:700,fontSize:11.5,cursor:'pointer'};const overlay:React.CSSProperties={position:'fixed',inset:0,zIndex:100,background:'rgba(0,0,0,.45)',display:'grid',placeItems:'center',padding:16};const tabBtn=(active:boolean):React.CSSProperties=>({...baseBtn,background:active?C.teal:'#fff',color:active?'#fff':C.muted,border:`1px solid ${active?C.teal:C.border}`});
